### ISSUE TITLE
Scenario editor crashes upon placing a unit with ambush (GNA #23834)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1502]
**[Original submission](https://gna.org/bugs/index.php?23834)** by anonymous on 2015-08-29

When placing various units on a field using the Unit Tool in the map/scenario editor, it seems to crash entirely upon a unit with ambush being placed, both Elvish Rangers and Woses. The following message is displayed in a popup window:

Assertion Failed!

Program: ...

File: src\unit_abilities.cpp

Line: 301

Expression: resources::units && resources::gameboard && resources::teams && resources::tod_manager

Both Abort and Ignore completely end the process, Ignore has it crash and offer debugging usage before ending the process as well.

The attached scenario file shows the environment in which I placed the unit - specifically being on side 2, in the column directly below the Elvish Sharpshooter - however, the specific side, location, or unit with Ambush did not seem to matter in my experimentation.

(Reproduced on Windows 10)
Release: 1.13
Priority: 5 - Normal
Severity: 4 - Important

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-08-29**

**anonymous added attachment:** [Units.cfg](http://gna.org/bugs/download.php?file_id=25017)

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-08-29**

**anonymous wrote:**

> Addendum: As it turns out this seems to affect all units with hiding abilites - namely submerge, nightstalk, and concealment, in addition to ambush.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-02-29**

**vultraz wrote:**

> Seems to affect all units, period.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-08**

**stikonas wrote:**

> Backtrace:
> 
> 
> 
> Program received signal SIGSEGV, Segmentation fault.
> 
> 0x000000000242a858 in std::_Hashtable<map_location, std::pair<map_location const, std::_Rb_tree_iterator<std::pair<unsigned long const, unit_map::unit_pod> > >, std::allocator<std::pair<map_location const, std::_Rb_tree_iterator<std::pair<unsigned long const, unit_map::unit_pod> > > >, std::__detail::_Select1st, std::equal_to<map_location>, std::hash<map_location>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_bucket_index (this#0x80, __k..., __c=427986)
> 
>     at /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/hashtable.h:621
> 
> 621           { return __hash_code_base::_M_bucket_index(__k, __c, _M_bucket_count); }
> 
> (gdb) backtrace
> 
> #0  0x000000000242a858 in std::_Hashtable<map_location, std::pair<map_location const, std::_Rb_tree_iterator<std::pair<unsigned long const, unit_map::unit_pod> > >, std::allocator<std::pair<map_location const, std::_Rb_tree_iterator<std::pair<unsigned long const, unit_map::unit_pod> > > >, std::__detail::_Select1st, std::equal_to<map_location>, std::hash<map_location>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_bucket_index (this#0x80, __k..., __c=427986)
> 
>     at /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/hashtable.h:621
> 
> #1  0x0000000002e8ea67 in std::_Hashtable<map_location, std::pair<map_location const, std::_Rb_tree_iterator<std::pair<unsigned long const, unit_map::unit_pod> > >, std::allocator<std::pair<map_location const, std::_Rb_tree_iterator<std::pair<unsigned long const, unit_map::unit_pod> > > >, std::__detail::_Select1st, std::equal_to<map_location>, std::hash<map_location>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find (this#0x80, __k...)
> 
>     at /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/hashtable.h:1306
> 
> #2  0x0000000002e8e42f in std::unordered_map<map_location, std::_Rb_tree_iterator<std::pair<unsigned long const, unit_map::unit_pod> >, std::hash<map_location>, std::equal_to<map_location>, std::allocator<std::pair<map_location const, std::_Rb_tree_iterator<std::pair<unsigned long const, unit_map::unit_pod> > > > >::find (this#0x80, __x...)
> 
>     at /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/unordered_map.h:615
> 
> #3  0x0000000002e8d1f8 in unit_map::find (this#0x50, loc...) at /home/andrius/repositories/wesnoth/src/units/map.cpp:294
> 
> #4  0x000000000241ffa3 in unit_map::find (this#0x50, loc...) at /home/andrius/repositories/wesnoth/src/units/map.hpp:296
> 
> #5  0x0000000002e2bb5d in unit::get_ability_bool (this#0x82d0be0, tag_name"hides", loc#..., dc...) at /home/andrius/repositories/wesnoth/src/units/abilities.cpp:145
> 
> 
> 
> #6  0x0000000002ec8b81 in unit::invisible (this#0x82d0be0, loc..., dc#..., see_alltrue) at /home/andrius/repositories/wesnoth/src/units/unit.cpp:2304
> 
> #7  0x0000000002e6c7ff in unit_drawer::redraw_unit (this#0x7fffffffbb20, u...) at /home/andrius/repositories/wesnoth/src/units/drawer.cpp:106
> 
> #8  0x00000000030fa5b6 in display::draw_invalidated (this=0x4270420) at /home/andrius/repositories/wesnoth/src/display.cpp:2567
> 
> #9  0x00000000030f9f12 in display::draw (this#0x4270420, updatetrue, force=false) at /home/andrius/repositories/wesnoth/src/display.cpp:2495
> 
> #10 0x00000000030f9d02 in display::draw (this=0x4270420) at /home/andrius/repositories/wesnoth/src/display.cpp:2442
> 
> #11 0x0000000003115481 in events::raise_draw_event () at /home/andrius/repositories/wesnoth/src/events.cpp:664
> 
> #12 0x0000000002683389 in controller_base::play_slice (this#0x7fffffffbe80, is_delay_enabledtrue) at /home/andrius/repositories/wesnoth/src/controller_base.cpp:212
> 
> #13 0x00000000026a4682 in editor::editor_controller::main_loop (this=0x7fffffffbe80) at /home/andrius/repositories/wesnoth/src/editor/controller/editor_controller.cpp:173
> 
> #14 0x00000000026b97da in editor::start (game_conf#..., video..., filename#"", take_screenshotfalse, screenshot_filename="map_screenshot.bmp")
> 
>     at /home/andrius/repositories/wesnoth/src/editor/editor_main.cpp:52
> 
> #15 0x000000000284e607 in game_launcher::start_editor (this#0x3ded160, filename"") at /home/andrius/repositories/wesnoth/src/game_launcher.cpp:991
> 
> #16 0x00000000023d519e in game_launcher::start_editor (this=0x3ded160) at /home/andrius/repositories/wesnoth/src/game_launcher.hpp:92
> 
> #17 0x00000000023d1a7f in do_gameloop (args#std::vector of length 1, capacity 1  {...}) at /home/andrius/repositories/wesnoth/src/wesnoth.cpp:821
> 
> #18 0x00000000023d23e9 in main (argc#1, argv0x7fffffffd148) at /home/andrius/repositories/wesnoth/src/wesnoth.cpp:1051

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-08**

**vultraz changed status:** None -> Ready For Test

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-08**

**vultraz changed status:** Ready For Test -> Fixed

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-08**

**vultraz wrote:**

> Just FTR, fixed here:
> 
> 
> 
> https://github.com/wesnoth/wesnoth/commit/7364d728600ecd518053e09ac5495551042cb4a9
> 
> https://github.com/wesnoth/wesnoth/commit/4bc0ac0041c3e7bf928d8057ac94fc508e6ef0e4
> 
> https://github.com/wesnoth/wesnoth/commit/eaea9be1177398b2fe1d06739c2eb43d1bd204e0
