### ISSUE TITLE
SDL2 + OpenGL crash on ARM (GNA #25378)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1615]
**[Original submission](https://gna.org/bugs/index.php?25378)** by petevine on 2016-12-10

Unlike in the previous issue, an OpenGL-only SDL2 library seems to be working fine input-wise but the game quickly crashes (the first block of info comes from the glshim/gl4es library):

$ ./wesnoth

Battle for Wesnoth v1.13.6+dev (66494fc-Clean)

Started on Sat Dec 10 22:29:25 2016

Automatically found a possible data directory at /home/odroid/wesnoth-master/build-boost154/..

LIBGL: Initialising gl4es

LIBGL: v0.9.2 built on Dec  3 2016 23:26:50

LIBGL:loaded: libGLESv1_CM.so

LIBGL:loaded: libEGL.so

LIBGL: Extension GL_OES_point_sprite detected and used

LIBGL: Extension GL_OES_point_size_array detected

LIBGL: Extension GL_OES_framebuffer_object detected and used

LIBGL: Extension GL_OES_packed_depth_stencil detected and used

LIBGL: Extension GL_OES_depth24 detected and used

LIBGL: Extension GL_OES_rgb8_rgba8 detected and used

LIBGL: Extension GL_EXT_texture_format_BGRA8888 detected

LIBGL: Extension GL_OES_depth_texture detected and used

LIBGL: Extension GL_OES_texture_cube_map detected and used

LIBGL: Max texture size: 4096

LIBGL: Texture Units: 8, Max lights: 8

LIBGL: Implementation Read is GL_RGB/GL_UNSIGNED_SHORT_5_6_5

LIBGL: Current folder is:/home/odroid/wesnoth-master/build-boost155

glXGetProcAddress: glXGetSwapIntervalMESA not found.

Data directory:               /home/odroid/wesnoth-master/build-boost154/..

User configuration directory: /home/odroid/.config/wesnoth

User data directory:          /home/odroid/.local/share/wesnoth/1.13

Cache directory:              /home/odroid/.cache/wesnoth

Setting mode to 1280x1024

Checking lua scripts... ok

20161210 22:29:29 error general: Unknown key: +

20161210 22:29:29 error general: Unknown key: page up

20161210 22:29:29 error general: Unknown key: page down

20161210 22:29:29 error general: Unknown key: :

wesnoth: /home/odroid/wesnoth-master/src/gui/widgets/menu_button.cpp:180: void gui2::menu_button::set_values(const std::vector<config>&, int): Assertion `static_cast<size_t>(selected) < values.size()' failed.

Aborted

(Reproduced on Linux)
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-12-12**

**petevine wrote:**

> Here's a trace from a debug build (gcc 4.9.4, boost 1.54, SDL 2.0.5):
> 
> 
> 
> #0  __libc_do_syscall () at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
> 
> #1  0xb6824ebe in __GI_raise (sig#sig@entry6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
> 
> #2  0xb6827716 in __GI_abort () at abort.c:89
> 
> #3  0xb6820104 in __assert_fail_base (fmt#0x1 <error: Cannot access memory at address 0x1>, assertion0x263bb4c "static_cast<size_t>(selected) < values.size()", 
> 
>     assertion@entry#0x0, file0x263bb00 "../src/gui/widgets/menu_button.cpp", file@entry#0xb4ab2000 "\001", line180, line@entry=3062735012, 
> 
>     function#function@entry0x263c01c <gui2::menu_button::set_values(std::vector<config, std::allocator<config> > const&, int)::__PRETTY_FUNCTION__> "void gui2::menu_button::set_values(const std::vector<config>&, int)") at assert.c:92
> 
> #4  0xb682019a in __GI___assert_fail (assertion#0x0, file0xb4ab2000 "\001", line=3062735012, 
> 
>     function=0x263c01c <gui2::menu_button::set_values(std::vector<config, std::allocator<config> > const&, int)::__PRETTY_FUNCTION__> "void gui2::menu_button::set_values(const std::vector<config>&, int)") at assert.c:101
> 
> #5  0x0197a2dc in gui2::menu_button::set_values (this#0x2cccb30, valuesstd::vector of length 3, capacity 4 # {...}, selected3)
> 
>     at ../src/gui/widgets/menu_button.cpp:180
> 
> #6  0x01fc842c in gui2::dialogs::preferences_dialog::post_build (this#0xbeffe184, window...) at ../src/gui/dialogs/preferences_dialog.cpp:637
> 
> #7  0x01f6a7dc in gui2::dialogs::modal_dialog::show (this#0xbeffe184, video..., auto_close_time=0) at ../src/gui/dialogs/modal_dialog.cpp:60
> 
> #8  0x01cc0b48 in gui2::dialogs::preferences_dialog::display (video#..., game_cfg..., initial_view=preferences::VIEW_DEFAULT)
> 
>     at ../src/gui/dialogs/preferences_dialog.hpp:76
> 
> #9  0x01e8653c in game_launcher::show_preferences (this=0x2986fa0) at ../src/game_launcher.cpp:923
> 
> #10 0x01ff4948 in gui2::dialogs::title_screen::<lambda(gui2::window&)>::operator()(gui2::window &) const (__closure=0x2bdff78)
> 
>     at ../src/gui/dialogs/title_screen.cpp:445
> 
> #11 0x01ff7f54 in std::_Function_handler<void(gui2::window&), gui2::dialogs::title_screen::pre_show(gui2::window&)::<lambda(gui2::window&)> >::_M_invoke(const std::_Any_data &, gui2::window &) (__functor#..., __args#0...) at /usr/include/c++/4.9/functional:2039
> 
> #12 0x01ff9a98 in std::function<void (gui2::window&)>::operator()(gui2::window&) const (this#0x2d23320, __args#0...) at /usr/include/c++/4.9/functional:2440
> 
> #13 0x01ff3bc4 in gui2::dialogs::<lambda(gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&)>::operator()(gui2::event::dispatcher &, gui2::event::ui_event, bool &, bool &) const (__closure#0x2d23320, w...) at ../src/gui/dialogs/title_screen.cpp:164
> 
> #14 0x01ff724c in std::_Function_handler<void(gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&), gui2::dialogs::register_button(gui2::window&, const string&, hotkey::HOTKEY_COMMAND, gui2::dialogs::btn_callback)::<lambda(gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&)> >::_M_invoke(const std::_Any_data &, gui2::event::dispatcher &, gui2::event::ui_event, bool &, bool &) (__functor#..., __args#0..., __args#1#gui2::event::LEFT_BUTTON_CLICK, __args#2@0xbeffe302: true, __args#3=@0xbeffe303: false)
> 
>     at /usr/include/c++/4.9/functional:2039
> 
> #15 0x01809730 in std::function<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&)>::operator()(gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&) const (this#0xbeffe31c, __args#0..., __args#1#gui2::event::LEFT_BUTTON_CLICK, __args#2@0xbeffe302: true, __args#3=@0xbeffe303: false) at /usr/include/c++/4.9/functional:2440
> 
> #16 0x01808e84 in gui2::event::trigger::operator()(std::function<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&)>, gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&) (this#0xbeffe338, functor..., dispatcher#..., eventgui2::event::LEFT_BUTTON_CLICK, handled#@0xbeffe302: true, halt@0xbeffe303: false)
> 
>     at ../src/gui/core/event/dispatcher.cpp:140
> 
> #17 0x0180bb0c in gui2::event::implementation::fire_event<std::function<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&)>, gui2::event::trigger>(gui2::event::ui_event, std::vector<std::pair<gui2::widget*, gui2::event::ui_event>, std::allocator<std::pair<gui2::widget*, gui2::event::ui_event> > >&, gui2::widget*, gui2::widget*, gui2::event::trigger) (event#gui2::event::LEFT_BUTTON_CLICK, event_chainstd::vector of length 0, capacity 0, dispatcher#0x2e16878, w0x2c75c18, functor=...)
> 
>     at ../src/gui/core/event/dispatcher_private.hpp:449
> 
> #18 0x01809f0c in gui2::event::fire_event<std::function<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&)>, gui2::event::trigger>(gui2::event::ui_event, gui2::widget*, gui2::widget*, gui2::event::trigger) (event#gui2::event::LEFT_BUTTON_CLICK, dispatcher0x2e16878, w#0x2c75c18, functor...)
> 
>     at ../src/gui/core/event/dispatcher_private.hpp:529
> 
> #19 0x01808418 in gui2::event::dispatcher::fire (this#0x2e16880, eventgui2::event::LEFT_BUTTON_CLICK, target=...)
> 
>     at ../src/gui/core/event/dispatcher.cpp:174
> 
> #20 0x01831db8 in gui2::event::mouse_button<(gui2::event::ui_event)7, (gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12>::mouse_button_click (this#0x2aaee48, widget0x2c75c18) at ../src/gui/core/event/distributor.cpp:593
> 
> #21 0x0182cd6c in gui2::event::mouse_button<(gui2::event::ui_event)7, (gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12>::signal_handler_sdl_button_up (this#0x2aaee48, eventgui2::event::SDL_LEFT_BUTTON_UP, handled#@0xbeffe52a: false, coordinate...)
> 
>     at ../src/gui/core/event/distributor.cpp:551
> 
> #22 0x01839abc in std::_Mem_fn<void (gui2::event::mouse_button<(gui2::event::ui_event)7, (gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12>::*)(gui2::event::ui_event, bool&, gui2::point const&)>::operator()<gui2::event::ui_event, bool&, gui2::point const&, void>(gui2::event::mouse_button<(gui2::event::ui_event)7, (gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12>*, gui2::event::ui_event&&, bool&, gui2::point const&) const (this#0x2be0008, __object0x2aaee48) at /usr/include/c++/4.9/functional:569
> 
> #23 0x018389d4 in std::_Bind<std::_Mem_fn<void (gui2::event::mouse_button<(gui2::event::ui_event)7, (gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12>::*)(gui2::event::ui_event, bool&, gui2::point const&)> (gui2::event::mouse_button<(gui2::event::ui_event)7, (gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12>*, boost::arg<2>, boost::arg<3>, boost::arg<5>)>::__call<void, gui2::event::dispatcher&, gui2::event::ui_event&&, bool&, bool&, gui2::point const&, 0u, 1u, 2u, 3u>(std::tuple<gui2::event::dispatcher&, gui2::event::ui_event&&, bool&, bool&, gui2::point const&>&&, std::_Index_tuple<0u, 1u, 2u, 3u>) (this#0x2be0008, __args<unknown type in ../build-4.9-new/wesnoth, CU 0xee9ad, DIE 0x12b9cb>)
> 
>     at /usr/include/c++/4.9/functional:1264
> 
> #24 0x01836254 in std::_Bind<std::_Mem_fn<void (gui2::event::mouse_button<(gui2::event::ui_event)7, (gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12>::*)(gui2::event::ui_event, bool&, gui2::point const&)> (gui2::event::mouse_button<(gui2::event::ui_event)7, (gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12>*, boost::arg<2>, boost::arg<3>, boost::arg<5>)>::operator()<gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&, gui2::point const&, void>(gui2::event::dispatcher&, gui2::event::ui_event&&, bool&, bool&, gui2::point const&) (
> 
>     this=0x2be0008) at /usr/include/c++/4.9/functional:1323
> 
> #25 0x01831a2c in std::_Function_handler<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&, gui2::point const&), std::_Bind<std::_Mem_fn<void (gui2::event::mouse_button<(gui2::event::ui_event)7, (gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12>::*)(gui2::event::ui_event, bool&, gui2::point const&)> (gui2::event::mouse_button<(gui2::event::ui_event)7, (gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12>*, boost::arg<2>, boost::arg<3>, boost::arg<5>)> >::_M_invoke(std::_Any_data const&, gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&, gui2::point const&) (__functor#..., __args#0..., __args#1#gui2::event::SDL_LEFT_BUTTON_UP, __args#2@0xbeffe52a: false, __args#3=@0xbeffe52b: false, 
> 
>     __args#4=...) at /usr/include/c++/4.9/functional:2039
> 
> #26 0x01809ffc in std::function<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&, gui2::point const&)>::operator()(gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&, gui2::point const&) const (this#0xbeffe544, __args#0..., __args#1#gui2::event::SDL_LEFT_BUTTON_UP, __args#2@0xbeffe52a: false, __args#3=@0xbeffe52b: false, 
> 
>     __args#4=...) at /usr/include/c++/4.9/functional:2440
> 
> #27 0x01808ef4 in gui2::event::trigger_mouse::operator()(std::function<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&, gui2::point const&)>, gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&) (this#0xbeffe560, functor..., dispatcher#..., eventgui2::event::SDL_LEFT_BUTTON_UP, handled=@0xbeffe52a: false, 
> 
>     halt=@0xbeffe52b: false) at ../src/gui/core/event/dispatcher.cpp:192
> 
> #28 0x0180c3b0 in gui2::event::implementation::fire_event<std::function<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&, gui2::point const&)>, gui2::event::trigger_mouse>(gui2::event::ui_event, std::vector<std::pair<gui2::widget*, gui2::event::ui_event>, std::allocator<std::pair<gui2::widget*, gui2::event::ui_event> > >&, gui2::widget*, gui2::widget*, gui2::event::trigger_mouse) (event#gui2::event::SDL_LEFT_BUTTON_UP, event_chainstd::vector of length 0, capacity 0, dispatcher#0x2e16878, w0x2e16878, 
> 
>     functor=...) at ../src/gui/core/event/dispatcher_private.hpp:449
> 
> #29 0x0180a0e4 in gui2::event::fire_event<std::function<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&, gui2::point const&)>, gui2::event::trigger_mouse>(gui2::event::ui_event, gui2::widget*, gui2::widget*, gui2::event::trigger_mouse) (event#gui2::event::SDL_LEFT_BUTTON_UP, dispatcher0x2e16878, w#0x2e16878, functor...)
> 
>     at ../src/gui/core/event/dispatcher_private.hpp:529
> 
> #30 0x018084d8 in gui2::event::dispatcher::fire (this#0x2e16880, eventgui2::event::SDL_LEFT_BUTTON_UP, target#..., coordinate...)
> 
>     at ../src/gui/core/event/dispatcher.cpp:206
> 
> #31 0x0183bed8 in gui2::event::sdl_event_handler::mouse (this#0x2a708e8, eventgui2::event::SDL_LEFT_BUTTON_UP, position=...)
> 
>     at ../src/gui/core/event/handler.cpp:559
> 
> #32 0x0183c008 in gui2::event::sdl_event_handler::mouse_button_up (this#0x2a708e8, position..., button=1 '\001')
> 
>     at ../src/gui/core/event/handler.cpp:578
> 
> #33 0x0183b2a8 in gui2::event::sdl_event_handler::handle_event (this#0x2a708e8, event...) at ../src/gui/core/event/handler.cpp:340
> 
> #34 0x024a6f80 in events::pump () at ../src/events.cpp:608
> 
> #35 0x01a32708 in gui2::window::show (this#0x2e16878, restorefalse, auto_close_timeout=0) at ../src/gui/widgets/window.cpp:639
> 
> #36 0x01f6a898 in gui2::dialogs::modal_dialog::show (this#0xbeffe8e8, video..., auto_close_time=0) at ../src/gui/dialogs/modal_dialog.cpp:70
> 
> #37 0x017d3ea4 in do_gameloop (args#std::vector of length 1, capacity 1  {...}) at ../src/wesnoth.cpp:795
> 
> #38 0x017d4964 in main (argc#1, argv0xbeffef34) at ../src/wesnoth.cpp:1062

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-01-06**

**petevine wrote:**

> A month later and starting from a fresh .config directory (didn't help at the time of the original submission) the game seems to be working fine. 
> 
> 
> 
> Please close.
