### ISSUE TITLE
memleak: MP post create game screen (GNA #25677)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1668]
**[Original submission](https://gna.org/bugs/index.php?25677)** by matthiaskrgr on 2017-04-26

Multiplayer

Local Game

[Esc]

Quit Game

=>

Direct leak of 296 byte(s) in 1 object(s) allocated from:

    #0 0x1977292 in operator new(unsigned long) /home/matthias/LLVM/LLVM_dev/stage_2/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:82:35

    #1 0x1d61833 in preprocess_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, preproc_define, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, preproc_define> > >*) /home/matthias/vcs/github/wesnoth/build/../src/serialization/preprocessor.cpp:1348:36

    #2 0x40e1547 in ng::create_engine::init_all_levels() /home/matthias/vcs/github/wesnoth/build/../src/game_initialization/create_engine.cpp:700:18

    #3 0x40dec07 in ng::create_engine::create_engine(CVideo&, saved_game&) /home/matthias/vcs/github/wesnoth/build/../src/game_initialization/create_engine.cpp:267:2

    #4 0x32aaf2c in enter_create_mode(std::shared_ptr<mp_workflow_helper>) /home/matthias/vcs/github/wesnoth/build/../src/game_initialization/multiplayer.cpp:442:21

    #5 0x32aa835 in mp::start_local_game(CVideo&, config const&, saved_game&) /home/matthias/vcs/github/wesnoth/build/../src/game_initialization/multiplayer.cpp:611:2

    #6 0x20e4ba0 in game_launcher::play_multiplayer(game_launcher::mp_selection) /home/matthias/vcs/github/wesnoth/build/../src/game_launcher.cpp:836:4

    #7 0x197d518 in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /home/matthias/vcs/github/wesnoth/build/../src/wesnoth.cpp:810:14

    #8 0x197a7e0 in main /home/matthias/vcs/github/wesnoth/build/../src/wesnoth.cpp:1053:19

    #9 0x7f02ed70a400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

(Reproduced on linux)
Release: v1.13.7+dev (e5cb8c4)
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-27**

**matthiaskrgr wrote:**

> This was fixed by c41aafd96dfe618d35353701a65973ec7bcc610d
> 
> Thanks!

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-27**

**vultraz changed status:** None -> Fixed
