### ISSUE TITLE
test scenario: memleak

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#1680]
wesnoth 45c1dec

This happene somewhere while poking around in test scenario. I'll have to dig around a bit to find a recipe.

````
Direct leak of 336 byte(s) in 6 object(s) allocated from:
    #0 0x196d5e2 in operator new(unsigned long) /home/matthias/LLVM/LLVM_dev/stage_2/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:82:35
    #1 0x1f35b8c in wfl::formula::formula(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, wfl::function_symbol_table*) /home/matthias/vcs/github/wesnoth/build/../src/formula/formula.cpp:75:14
    #2 0x31bf833 in do_interpolation(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, variable_set const&) /home/matthias/vcs/github/wesnoth/build/../src/formula/string_utils.cpp:118:24
    #3 0x31c0887 in utils::interpolate_variables_into_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, variable_set const&) /home/matthias/vcs/github/wesnoth/build/../src/formula/string_utils.cpp:229:9
    #4 0x29de119 in (anonymous namespace)::vconfig_expand_visitor::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /home/matthias/vcs/github/wesnoth/build/../src/variable.cpp:293:13
    #5 0x29de119 in void boost::detail::variant::invoke_visitor<(anonymous namespace)::vconfig_expand_visitor const>::internal_visit<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /usr/include/boost/variant/variant.hpp:978
    #6 0x29de119 in boost::detail::variant::invoke_visitor<(anonymous namespace)::vconfig_expand_visitor const>::result_type boost::detail::variant::visitation_impl_invoke_impl<boost::detail::variant::invoke_visitor<(anonymous namespace)::vconfig_expand_visitor const>, void const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(int, boost::detail::variant::invoke_visitor<(anonymous namespace)::vconfig_expand_visitor const>&, void const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, mpl_::bool_<true>) /usr/include/boost/variant/detail/visitation_impl.hpp:112
    #7 0x29de119 in boost::detail::variant::invoke_visitor<(anonymous namespace)::vconfig_expand_visitor const>::result_type boost::detail::variant::visitation_impl_invoke<boost::detail::variant::invoke_visitor<(anonymous namespace)::vconfig_expand_visitor const>, void const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::variant<boost::blank, config::attribute_value::true_false, config::attribute_value::yes_no, int, unsigned long long, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, t_string>::has_fallback_type_>(int, boost::detail::variant::invoke_visitor<(anonymous namespace)::vconfig_expand_visitor const>&, void const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, boost::variant<boost::blank, config::attribute_value::true_false, config::attribute_value::yes_no, int, unsigned long long, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, t_string>::has_fallback_type_, int) /usr/include/boost/variant/detail/visitation_impl.hpp:154
    #8 0x29de119 in boost::detail::variant::invoke_visitor<(anonymous namespace)::vconfig_expand_visitor const>::result_type boost::detail::variant::visitation_impl<mpl_::int_<0>, boost::detail::variant::visitation_impl_step<boost::mpl::l_iter<boost::mpl::l_item<mpl_::long_<8l>, boost::blank, boost::mpl::l_item<mpl_::long_<7l>, config::attribute_value::true_false, boost::mpl::l_item<mpl_::long_<6l>, config::attribute_value::yes_no, boost::mpl::l_item<mpl_::long_<5l>, int, boost::mpl::l_item<mpl_::long_<4l>, unsigned long long, boost::mpl::l_item<mpl_::long_<3l>, double, boost::mpl::l_item<mpl_::long_<2l>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::mpl::l_item<mpl_::long_<1l>, t_string, boost::mpl::l_end> > > > > > > > >, boost::mpl::l_iter<boost::mpl::l_end> >, boost::detail::variant::invoke_visitor<(anonymous namespace)::vconfig_expand_visitor const>, void const*, boost::variant<boost::blank, config::attribute_value::true_false, config::attribute_value::yes_no, int, unsigned long long, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, t_string>::has_fallback_type_>(int, int, boost::detail::variant::invoke_visitor<(anonymous namespace)::vconfig_expand_visitor const>&, void const*, mpl_::bool_<false>, boost::variant<boost::blank, config::attribute_value::true_false, config::attribute_value::yes_no, int, unsigned long long, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, t_string>::has_fallback_type_, mpl_::int_<0>*, boost::detail::variant::visitation_impl_step<boost::mpl::l_iter<boost::mpl::l_item<mpl_::long_<8l>, boost::blank, boost::mpl::l_item<mpl_::long_<7l>, config::attribute_value::true_false, boost::mpl::l_item<mpl_::long_<6l>, config::attribute_value::yes_no, boost::mpl::l_item<mpl_::long_<5l>, int, boost::mpl::l_item<mpl_::long_<4l>, unsigned long long, boost::mpl::l_item<mpl_::long_<3l>, double, boost::mpl::l_item<mpl_::long_<2l>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::mpl::l_item<mpl_::long_<1l>, t_string, boost::mpl::l_end> > > > > > > > >, boost::mpl::l_iter<boost::mpl::l_end> >*) /usr/include/boost/variant/detail/visitation_impl.hpp:238
    #9 0x29de119 in boost::detail::variant::invoke_visitor<(anonymous namespace)::vconfig_expand_visitor const>::result_type boost::variant<boost::blank, config::attribute_value::true_false, config::attribute_value::yes_no, int, unsigned long long, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, t_string>::internal_apply_visitor_impl<boost::detail::variant::invoke_visitor<(anonymous namespace)::vconfig_expand_visitor const>, void const*>(int, int, boost::detail::variant::invoke_visitor<(anonymous namespace)::vconfig_expand_visitor const>&, void const*) /usr/include/boost/variant/variant.hpp:2321
    #10 0x29de119 in boost::detail::variant::invoke_visitor<(anonymous namespace)::vconfig_expand_visitor const>::result_type boost::variant<boost::blank, config::attribute_value::true_false, config::attribute_value::yes_no, int, unsigned long long, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, t_string>::internal_apply_visitor<boost::detail::variant::invoke_visitor<(anonymous namespace)::vconfig_expand_visitor const> >(boost::detail::variant::invoke_visitor<(anonymous namespace)::vconfig_expand_visitor const>&) const /usr/include/boost/variant/variant.hpp:2346
    #11 0x29de119 in (anonymous namespace)::vconfig_expand_visitor const::result_type boost::variant<boost::blank, config::attribute_value::true_false, config::attribute_value::yes_no, int, unsigned long long, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, t_string>::apply_visitor<(anonymous namespace)::vconfig_expand_visitor const>((anonymous namespace)::vconfig_expand_visitor const&) const /usr/include/boost/variant/variant.hpp:2370
    #12 0x29de119 in (anonymous namespace)::vconfig_expand_visitor::result_type boost::apply_visitor<(anonymous namespace)::vconfig_expand_visitor, boost::variant<boost::blank, config::attribute_value::true_false, config::attribute_value::yes_no, int, unsigned long long, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, t_string> const>((anonymous namespace)::vconfig_expand_visitor const&, boost::variant<boost::blank, config::attribute_value::true_false, config::attribute_value::yes_no, int, unsigned long long, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, t_string> const&) /usr/include/boost/variant/detail/apply_visitor_unary.hpp:84
    #13 0x29de119 in (anonymous namespace)::vconfig_expand_visitor::result_type config::attribute_value::apply_visitor<(anonymous namespace)::vconfig_expand_visitor>((anonymous namespace)::vconfig_expand_visitor const&) const /home/matthias/vcs/github/wesnoth/build/../src/config.hpp:389
    #14 0x29db31e in vconfig::expand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /home/matthias/vcs/github/wesnoth/build/../src/variable.cpp:306:7
    #15 0x265e219 in vconfig::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /home/matthias/vcs/github/wesnoth/build/../src/variable.hpp:89:11
    #16 0x265e219 in lua_common::impl_vconfig_get(lua_State*) /home/matthias/vcs/github/wesnoth/build/../src/scripting/lua_common.cpp:248
    #17 0x44494cc in luaD_precall(lua_State*, lua_TValue*, int) /home/matthias/vcs/github/wesnoth/build/../src/lua/ldo.cpp:365:11
    #18 0x444c430 in luaD_call(lua_State*, lua_TValue*, int) /home/matthias/vcs/github/wesnoth/build/../src/lua/ldo.cpp:495:8
    #19 0x44acc54 in luaT_callTM(lua_State*, lua_TValue const*, lua_TValue const*, lua_TValue const*, lua_TValue*, int) /home/matthias/vcs/github/wesnoth/build/../src/lua/ltm.cpp:114:5
    #20 0x44b5619 in luaV_finishget(lua_State*, lua_TValue const*, lua_TValue*, lua_TValue*, lua_TValue const*) /home/matthias/vcs/github/wesnoth/build/../src/lua/lvm.cpp:182:7
    #21 0x44cd468 in luaV_execute(lua_State*) /home/matthias/vcs/github/wesnoth/build/../src/lua/lvm.cpp:845:9
    #22 0x444c43c in luaD_call(lua_State*, lua_TValue*, int) /home/matthias/vcs/github/wesnoth/build/../src/lua/ldo.cpp:496:5
    #23 0x444c5dc in luaD_callnoyield(lua_State*, lua_TValue*, int) /home/matthias/vcs/github/wesnoth/build/../src/lua/ldo.cpp:506:3
    #24 0x442b7ed in f_call(lua_State*, void*) /home/matthias/vcs/github/wesnoth/build/../src/lua/lapi.cpp:942:3
    #25 0x444609e in luaD_rawrunprotected(lua_State*, void (*)(lua_State*, void*), void*) /home/matthias/vcs/github/wesnoth/build/../src/lua/ldo.cpp:142:3
    #26 0x444ed95 in luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long) /home/matthias/vcs/github/wesnoth/build/../src/lua/ldo.cpp:727:12
    #27 0x442a830 in lua_pcallk(lua_State*, int, int, int, long, int (*)(lua_State*, int, long)) /home/matthias/vcs/github/wesnoth/build/../src/lua/lapi.cpp:968:14
    #28 0x2663930 in luaW_pcall_internal(lua_State*, int, int) /home/matthias/vcs/github/wesnoth/build/../src/scripting/lua_common.cpp:938:16
    #29 0x2663af1 in luaW_pcall(lua_State*, int, int, bool) /home/matthias/vcs/github/wesnoth/build/../src/scripting/lua_common.cpp:954:12
    #30 0x2613edc in game_lua_kernel::run_wml_action(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, vconfig const&, game_events::queued_event const&) /home/matthias/vcs/github/wesnoth/build/../src/scripting/game_lua_kernel.cpp:4477:2
    #31 0x403906f in game_events::event_handler::handle_event(game_events::queued_event const&, std::shared_ptr<game_events::event_handler>&, game_lua_kernel&) /home/matthias/vcs/github/wesnoth/build/../src/game_events/handlers.cpp:130:5
    #32 0x322846c in game_events::wml_event_pump::process_event(std::shared_ptr<game_events::event_handler>&, game_events::queued_event const&) /home/matthias/vcs/github/wesnoth/build/../src/game_events/pump.cpp:289:14
    #33 0x322d9a5 in game_events::wml_event_pump::operator()() /home/matthias/vcs/github/wesnoth/build/../src/game_events/pump.cpp:563:5
    #34 0x322c309 in game_events::wml_event_pump::fire(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, game_events::entity_location const&, game_events::entity_location const&, config const&) /home/matthias/vcs/github/wesnoth/build/../src/game_events/pump.cpp:467:9
    #35 0x2dad5fe in actions::(anonymous namespace)::unit_mover::post_move(actions::undo_list*) /home/matthias/vcs/github/wesnoth/build/../src/actions/move.cpp:1092:52
    #36 0x2da53e7 in actions::move_unit_internal(actions::undo_list*, bool, bool*, actions::(anonymous namespace)::unit_mover&) /home/matthias/vcs/github/wesnoth/build/../src/actions/move.cpp:1234:8
    #37 0x2da2478 in actions::move_unit_and_record(std::vector<map_location, std::allocator<map_location> > const&, actions::undo_list*, bool, bool, bool*, actions::move_unit_spectator*) /home/matthias/vcs/github/wesnoth/build/../src/actions/move.cpp:1301:15
    #38 0x3aabd62 in events::mouse_handler::move_unit_along_route(std::vector<map_location, std::allocator<map_location> > const&, bool&) /home/matthias/vcs/github/wesnoth/build/../src/mouse_events.cpp:850:17
    #39 0x3aa91ff in events::mouse_handler::move_unit_along_current_route() /home/matthias/vcs/github/wesnoth/build/../src/mouse_events.cpp:792:22

````

**Comment by matthiaskrgr** [comment]
This​ is caused by first moving on 'Open, Sesame!' (4,4) and then 'Crash Test' (1,2).

**Comment by CelticMinstrel** [comment]
I think the commit I pushed should fix it, but I can't even get that far on my build. I keep getting out of memory errors. I'm assuming it was introduced since the commit you referenced in your report and am going to bisect to try to find it.

**Comment by matthiaskrgr** [comment]
Fix confirmed. Thanks.

**Comment by CelticMinstrel** [comment]
Can you confirm again on 7b13d6ca?

**Comment by matthiaskrgr** [comment]
Yeah, still looking good.
