### ISSUE TITLE
Segfault in wesnothd when failing to create fifo file

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1757]
$ wesnothd-git -p 444
```
20170605 00:12:43 error server: could not make fifo at '/run/wesnothd-git/socket' (No such file or directory)
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  bind: Permission denied
Abgebrochen (Speicherabzug geschrieben)
```
This file doesn't exist, but it shouldn't segfault.
Backtrace:
```
#0  0x00007f6097aff670 in raise () from /usr/lib/libc.so.6
#1  0x00007f6097b00d00 in abort () from /usr/lib/libc.so.6
#2  0x00007f609842bfd5 in __gnu_cxx::__verbose_terminate_handler ()
    at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007f6098429be6 in __cxxabiv1::__terminate (handler=<optimized out>)
    at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007f6098429c31 in std::terminate () at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007f6098429e73 in __cxxabiv1::__cxa_throw (obj=<optimized out>, 
    tinfo=0x619cb8 <typeinfo for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >>, 
    dest=0x46f960 <boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >::~clone_impl()>) at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:93
#6  0x0000000000469cca in boost::throw_exception<boost::system::system_error> (e=...) at /usr/include/boost/throw_exception.hpp:69
#7  0x0000000000463ee5 in boost::asio::detail::do_throw_error (err=..., location=0x61b0be "bind")
    at /usr/include/boost/asio/detail/impl/throw_error.ipp:38
#8  0x0000000000463e44 in boost::asio::detail::throw_error (err=..., location=0x61b0be "bind")
    at /usr/include/boost/asio/detail/throw_error.hpp:42
#9  0x00000000004a335f in boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> >::bind (this=0x7fff85972070, endpoint=...) at /usr/include/boost/asio/basic_socket_acceptor.hpp:376
#10 0x000000000049b454 in server_base::start_server (this=0x7fff85972050) at src/server/server_base.cpp:52
#11 0x000000000044b13d in wesnothd::server::server (this=0x7fff85972050, port=444, keep_alive=false, config_file="")
    at src/server/server.cpp:261
#12 0x000000000046309e in main (argc=3, argv=0x7fff85972918) at src/server/server.cpp:2814

```

**Comment by loonycyborg** [comment]
The real cause error is "bind: Permission denied". Which means it failed to bind the server port. Port 444 is privileged(number below 1024) and user processes can't bind it. Though the error message definitely requires more work, true.

**Comment by sevu** [comment]
When you start the server with the wesnoth UI and leave the lobby again, it still runs.
When again starting the server that way, this message is shown in stderr and you join the lobby of the old server.
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  bind: Address already in use
```
Could this case be catched too.

**Comment by loonycyborg** [comment]
Currently "host networked game" automatically connects to existing local server even if wesnothd run by it fails to bind port. In fact at least on posix platforms client won't even see error status from failing to bind port because wesnothd run with -d option forks off before trying to bind port.
