### ISSUE TITLE
accelerated_rendering: help crashes

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#1822]
branch: accelerated_rendering @ d4d94a8

launch game
open the Help from the main menu => crash

````
Checking lua scripts... ok
../src/help/help.cpp:168:67: runtime error: member access within null pointer of type 'SDL_Surface'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/help/help.cpp:168:67 in 
ASAN:DEADLYSIGNAL
=================================================================
==15406==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x0000067ba7ff bp 0x7ffd8f9510c0 sp 0x7ffd8f94f380 T0)
==15406==The signal is caused by a READ memory access.
==15406==Hint: address points to the zero page.
    #0 0x67ba7fe in help::show_help(CVideo&, help::section const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int) /home/matthias/vcs/github/wesnoth/build/../src/help/help.cpp:168:67
    #1 0x67ba433 in help::show_help(CVideo&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int) /home/matthias/vcs/github/wesnoth/build/../src/help/help.cpp:118:2
    #2 0x5fe948d in gui2::dialogs::title_screen::pre_show(gui2::window&)::$_2::operator()(gui2::window&) const /home/matthias/vcs/github/wesnoth/build/../src/gui/dialogs/title_screen.cpp:322:3
    #3 0x5fe948d in std::_Function_handler<void (gui2::window&), gui2::dialogs::title_screen::pre_show(gui2::window&)::$_2>::_M_invoke(std::_Any_data const&, gui2::window&) /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/functional:1731
    #4 0x5ff2e2f in std::function<void (gui2::window&)>::operator()(gui2::window&) const /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/functional:2127:14
    #5 0x5fe7351 in gui2::dialogs::register_button(gui2::window&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, hotkey::HOTKEY_COMMAND, std::function<void (gui2::window&)>)::$_15::operator()(gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&) const /home/matthias/vcs/github/wesnoth/build/../src/gui/dialogs/title_screen.cpp:165:69
    #6 0x5fe7351 in std::_Function_handler<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&), gui2::dialogs::register_button(gui2::window&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, hotkey::HOTKEY_COMMAND, std::function<void (gui2::window&)>)::$_15>::_M_invoke(std::_Any_data const&, gui2::event::dispatcher&, gui2::event::ui_event&&, bool&, bool&) /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/functional:1731
    #7 0x5c0bdda in std::function<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&)>::operator()(gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&) const /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/functional:2127:14
    #8 0x5c0938d in bool gui2::event::implementation::fire_event<std::function<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&)>>(gui2::event::ui_event, std::vector<std::pair<gui2::widget*, gui2::event::ui_event>, std::allocator<std::pair<gui2::widget*, gui2::event::ui_event> > >&, gui2::widget*, gui2::widget*) /home/matthias/vcs/github/wesnoth/build/../src/gui/core/event/dispatcher_private.hpp:433:4
    #9 0x5bc3b03 in bool gui2::event::fire_event<std::function<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&)>>(gui2::event::ui_event, gui2::event::dispatcher*, gui2::widget*) /home/matthias/vcs/github/wesnoth/build/../src/gui/core/event/dispatcher_private.hpp:505:9
    #10 0x5bc05c9 in gui2::event::dispatcher::fire(gui2::event::ui_event, gui2::widget&) /home/matthias/vcs/github/wesnoth/build/../src/gui/core/event/dispatcher.cpp:137:11
    #11 0x6790497 in gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >::mouse_button_click(gui2::widget*) /home/matthias/vcs/github/wesnoth/build/../src/gui/core/event/distributor.cpp:526:10
    #12 0x678d9c6 in gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >::signal_handler_sdl_button_up(gui2::event::ui_event, bool&, gui2::point const&) /home/matthias/vcs/github/wesnoth/build/../src/gui/core/event/distributor.cpp:494:4
    #13 0x678fc28 in void std::__invoke_impl<void, void (gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >::* const&)(gui2::event::ui_event, bool&, gui2::point const&), gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >*&, gui2::event::ui_event, bool&, gui2::point const&>(std::__invoke_memfun_deref, void (gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >::* const&)(gui2::event::ui_event, bool&, gui2::point const&), gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >*&, gui2::event::ui_event&&, bool&, gui2::point const&) /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/functional:227:14
    #14 0x678f9fb in std::result_of<void (gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >::* const&(gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >*&, gui2::event::ui_event&&, bool&, gui2::point const&))(gui2::event::ui_event, bool&, gui2::point const&)>::type std::__invoke<void (gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >::* const&)(gui2::event::ui_event, bool&, gui2::point const&), gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >*&, gui2::event::ui_event, bool&, gui2::point const&>(void (gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >::* const&)(gui2::event::ui_event, bool&, gui2::point const&), gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >*&, gui2::event::ui_event&&, bool&, gui2::point const&) /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/functional:250:14
    #15 0x678f818 in _ZNKSt12_Mem_fn_baseIMN4gui25event12mouse_buttonINS1_32mouse_button_event_types_wrapperILNS1_8ui_eventE8ELS4_9ELS4_10ELS4_11ELS4_12ELS4_13EEEEEFvS4_RbRKNS0_5pointEELb1EEclIJRPS6_S4_S7_SA_EEEDTclsr3stdE8__invokedtdefpT6_M_pmfspclsr3stdE7forwardIT_Efp_EEEDpOSH_ /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/functional:604:11
    #16 0x678f5a8 in void std::_Bind<std::_Mem_fn<void (gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >::*)(gui2::event::ui_event, bool&, gui2::point const&)> (gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >*, boost::arg<2>, boost::arg<3>, boost::arg<5>)>::__call<void, gui2::event::dispatcher&, gui2::event::ui_event&&, bool&, bool&, gui2::point const&, 0ul, 1ul, 2ul, 3ul>(std::tuple<gui2::event::dispatcher&, gui2::event::ui_event&&, bool&, bool&, gui2::point const&>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/functional:933:11
    #17 0x678f342 in void std::_Bind<std::_Mem_fn<void (gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >::*)(gui2::event::ui_event, bool&, gui2::point const&)> (gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >*, boost::arg<2>, boost::arg<3>, boost::arg<5>)>::operator()<gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&, gui2::point const&, void>(gui2::event::dispatcher&, gui2::event::ui_event&&, bool&, bool&, gui2::point const&) /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/functional:991:17
    #18 0x678e9fe in std::_Function_handler<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&, gui2::point const&), std::_Bind<std::_Mem_fn<void (gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >::*)(gui2::event::ui_event, bool&, gui2::point const&)> (gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >*, boost::arg<2>, boost::arg<3>, boost::arg<5>)> >::_M_invoke(std::_Any_data const&, gui2::event::dispatcher&, gui2::event::ui_event&&, bool&, bool&, gui2::point const&) /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/functional:1731:2
    #19 0x5c113ea in std::function<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&, gui2::point const&)>::operator()(gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&, gui2::point const&) const /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/functional:2127:14
    #20 0x5c101fb in bool gui2::event::implementation::fire_event<std::function<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&, gui2::point const&)>, gui2::point const&>(gui2::event::ui_event, std::vector<std::pair<gui2::widget*, gui2::event::ui_event>, std::allocator<std::pair<gui2::widget*, gui2::event::ui_event> > >&, gui2::widget*, gui2::widget*, gui2::point const&) /home/matthias/vcs/github/wesnoth/build/../src/gui/core/event/dispatcher_private.hpp:433:4
    #21 0x5bc3d9f in bool gui2::event::fire_event<std::function<void (gui2::event::dispatcher&, gui2::event::ui_event, bool&, bool&, gui2::point const&)>, gui2::point const&>(gui2::event::ui_event, gui2::event::dispatcher*, gui2::widget*, gui2::point const&) /home/matthias/vcs/github/wesnoth/build/../src/gui/core/event/dispatcher_private.hpp:505:9
    #22 0x5bc07ed in gui2::event::dispatcher::fire(gui2::event::ui_event, gui2::widget&, gui2::point const&) /home/matthias/vcs/github/wesnoth/build/../src/gui/core/event/dispatcher.cpp:144:9
    #23 0x5bb2462 in gui2::event::sdl_event_handler::mouse(gui2::event::ui_event, gui2::point const&) /home/matthias/vcs/github/wesnoth/build/../src/gui/core/event/handler.cpp
    #24 0x5bb2b73 in gui2::event::sdl_event_handler::mouse_button_up(gui2::point const&, unsigned char) /home/matthias/vcs/github/wesnoth/build/../src/gui/core/event/handler.cpp
    #25 0x5bb0a90 in gui2::event::sdl_event_handler::handle_event(SDL_Event const&) /home/matthias/vcs/github/wesnoth/build/../src/gui/core/event/handler.cpp:322:4
    #26 0x4f216f3 in events::pump() /home/matthias/vcs/github/wesnoth/build/../src/events.cpp:678:14
    #27 0x6734594 in gui2::window::show(bool, unsigned int) /home/matthias/vcs/github/wesnoth/build/../src/gui/widgets/window.cpp:566:4
    #28 0x5e45e6d in gui2::dialogs::modal_dialog::show(CVideo&, unsigned int) /home/matthias/vcs/github/wesnoth/build/../src/gui/dialogs/modal_dialog.cpp:70:20
    #29 0x4abd32e in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /home/matthias/vcs/github/wesnoth/build/../src/wesnoth.cpp:801:8
    #30 0x4ab992d in main /home/matthias/vcs/github/wesnoth/build/../src/wesnoth.cpp:1067:19
    #31 0x7f2450a1b400 in __libc_start_main (/lib64/libc.so.6+0x20400)
    #32 0x49eb029 in _start (/home/matthias/vcs/github/wesnoth/build/wesnoth+0x49eb029)
````

**Comment by Vultraz** [comment]
Know. Probably will be an issue for awhile.

**Comment by Vultraz** [comment]
Crash fixed, but Help obv not drawing properly. Still, closing since the main issue is fixed.
