### ISSUE TITLE
wmlscope: UnboundLocalError with [/attack] without [attack]

### ISSUE THREAD

**Issue by ePaul** [wesnoth/wesnoth#2052]
**Wrong behavior**
When running wmlscope on a project containing a WML file with a `[/attack]` without a preceding `[attack]` (which currently happens in the Mountain Witch addon), the tool crashes with a traceback like this one:

```
Traceback (most recent call last):
  File "data/tools/wmlscope", line 443, in <module>
    xref = CrossRefLister(dirpath, "|".join(exclude), warnlevel, progress)
  File "/home/paulo/projektoj/wesnoth-dev/data/tools/wesnoth/wmltools3.py", line 798, in __init__
    if attack_name and not have_icon:
UnboundLocalError: local variable 'have_icon' referenced before assignment
```

**Reproducting**

Extract [bug-example.zip](https://github.com/wesnoth/wesnoth/files/1342341/bug-example.zip), and then run:

    data/tools/wmlscope bug-example/

**Expected behavior**
If invalid WML code is encountered, a useful error message (including the file name and line number of the problem) should be printed, not the script be crashing.

**Analysis**
This happens because of this piece of code in wmltools3.py:

```python
                        if state == "outside":
                            if "[attack]" in line:
                                beneath = 0
                                attack_name = default_icon = None
                                have_icon = False
                            elif "name=" in line and not "no-icon" in comment:
                                attack_name = line[line.find("name=")+5:].strip()
                                default_icon = os.path.join("attacks", attack_name  + ".png")
                            elif "icon=" in line and beneath == 0:
                                have_icon = True
                            elif "[/attack]" in line:
                                if attack_name and not have_icon:  # ← this is the error
                                    candidates = []
                                    key = None
                                    for trial in self.fileref:
                                        if trial.endswith(os.sep + default_icon) and self.visible_from(trial, fn, n):
                                            key = trial
                                            self.fileref[trial].append(fn, n+1)
                                            candidates.append(trial)
                                    if len(candidates) > 1:
                                        print("%s: more than one definition of %s is visible here (%s)." % (Reference(ns,fn, n), name, ", ".join(candidates)))
                                if not key:
                                    self.missing.append((default_icon, Reference(ns,fn,n+1)))
                            elif line.strip().startswith("[/"):
                                beneath -= 1
                            elif line.strip().startswith("["):
                                beneath += 1

```
The only occurrences of `have_icon` are in this section (which is executed once for each line in each file, I think). `have_icon` is only initialized at an `[attack]` or `icon=` line, but accessed at an `[/attack]` line.
This causes the behavior described above.

**Proposed fix**

I don't know enough about the actual functionality here (and python in general) to propose a fix.
Adding `have_icon = False` to the start of the method seems to get rid of this error, though I don't know whether this is the right place to do so.

**Comment by AI0867** [comment]
That is indeed the correct fix.
