### ISSUE TITLE
accessing help makes editor hang when quitting to desktop

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#2154]
Battle for Wesnoth v1.13.10+dev (61bbd51-Clean)
````
start wesnoth -e
File -> Help
Close
File->Quit to desktop
=> screen freezes, game does not terminate
````
ctrl+c works however

edit: tried to catch bt with gdb:
````
(gdb) bt full
#0  0x000000000496d300 in font::remove_floating_label(int) (handle=26) at ../src/floating_label.cpp:227
#1  0x000000000496dfa6 in font::floating_label_context::~floating_label_context() (this=<optimized out>) at ../src/floating_label.cpp:272
        context = std::set with 2 elements = {[0] = 26, [1] = 48}
#2  0x00000000055564e4 in std::default_delete<font::floating_label_context>::operator()(font::floating_label_context*) const (__ptr=0x60200084dd30, this=<optimized out>)
    at /usr/lib/gcc/x86_64-redhat-linux/6.4.1/../../../../include/c++/6.4.1/bits/unique_ptr.h:76
        __ptr = <optimized out>
#3  0x00000000055564e4 in std::unique_ptr<font::floating_label_context, std::default_delete<font::floating_label_context> >::~unique_ptr() (this=<optimized out>)
    at /usr/lib/gcc/x86_64-redhat-linux/6.4.1/../../../../include/c++/6.4.1/bits/unique_ptr.h:239
        __ptr = <optimized out>
#4  0x000000000553122e in editor::editor_controller::~editor_controller() (this=0x7fffffffc160) at ../src/editor/controller/editor_controller.cpp:168
Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
#5  0x0000000005450991 in editor::start(config const&, CVideo&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (game_conf=..., video=..., filename=..., take_screenshot=false, screenshot_filename=) at ../src/editor/editor_main.cpp:54
        e = <optimized out>
        e = <optimized out>
Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
#6  0x00000000052c2e72 in game_launcher::start_editor(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x61c000000080, filename=) at ../src/game_launcher.cpp:992
        res = <optimized out>
#7  0x00000000044d24c8 in game_launcher::start_editor() (this=0x61c000000080) at ../src/game_launcher.hpp:93
#8  0x00000000044c48b8 in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (args=warning: Type size unknown, assuming 1. Try casting to a known type, or void *.
warning: Type size unknown, assuming 1. Try casting to a known type, or void *.
Python Exception <class 'gdb.error'> Cannot perform pointer math on incomplete type "std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >", try casting to a known type, or void *.: 
std::vector of length -107477261290297, capacity -107477261615232) at ../src/wesnoth.cpp:826
        should_reload = game_launcher::RELOAD_DATA
        cmdline_opts = warning: Type size unknown, assuming 1. Try casting to a known type, or void *.
warning: Type size unknown, assuming 1. Try casting to a known type, or void *.
Python Exception <class 'gdb.error'> Cannot perform pointer math on incomplete type "std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >", try casting to a known type, or void *.: 

````

**Comment by Wedge009** [comment]
Confirmed in Windows (even without starting directly in editor). At a guess, it looks like something in the Help window is not allowing the application to close from the Editor. Returning to the title screen from the Editor still seems to work, though.
