### ISSUE TITLE
using the option -u . with . as directory does not work in wesnoth_addon_manager

### ISSUE THREAD

**Issue by elias-pschernig** [wesnoth/wesnoth#2494]
Using the full path to the current directory instead works.

**Comment by shikadilord** [comment]
To be precise, it results in a crash like this:

```
21:20:51 shadowm@hanacore ~/src/projects/After_the_Storm git:feature/naia-refactor % wesnoth_addon_manager -p 1.13.x -a localhost -u .
Opening socket to localhost:15008 for 1.13.x
Connected as 42.
Adding directory . as ..
('Ignored dir', '.')
Exception in thread None:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/shadowm/src/wesnoth/data/tools/wesnoth/campaignserver_client.py", line 398, in run
    self.data = self.cs.put_campaign(*self.args)
  File "/home/shadowm/src/wesnoth/data/tools/wesnoth/campaignserver_client.py", line 344, in put_campaign
    packet = self.make_packet(request)
  File "/home/shadowm/src/wesnoth/data/tools/wesnoth/campaignserver_client.py", line 122, in make_packet
    sorter(doc)
  File "/home/shadowm/src/wesnoth/data/tools/wesnoth/campaignserver_client.py", line 121, in sorter
    sorter(tag2)
  File "/home/shadowm/src/wesnoth/data/tools/wesnoth/campaignserver_client.py", line 119, in sorter
    tag.data.sort(key = lambda node: node.name)
  File "/home/shadowm/src/wesnoth/data/tools/wesnoth/campaignserver_client.py", line 119, in <lambda>
    tag.data.sort(key = lambda node: node.name)
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by vgaming** [comment]
created a PR for this issue.
