### ISSUE TITLE
editor crashes on launch

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#2816]
wesnoth 3f67c2fbf051aa9e322defb66c782477cd53b8bd
start wesnoth -e
````
Battle for Wesnoth v1.15.0-dev (3f67c2fbf0-Clean)
Started on Mon Apr  2 02:00:12 2018
Automatically found a possible data directory at /home/USER/vcs/github/wesnoth/build/..
Data directory:               /home/USER/vcs/github/wesnoth/build/..
User configuration directory: /home/USER/.config/wesnoth
User data directory:          /home/USER/.local/share/wesnoth/1.15
Cache directory:              /home/USER/.cache/wesnoth
Setting mode to 1340x1041
Checking lua scripts... ok
../src/terrain/builder.hpp:99:10: runtime error: reference binding to null pointer of type 'const gamemap'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/terrain/builder.hpp:99:10 in
../src/terrain/builder.cpp:1137:29: runtime error: member call on null pointer of type 'gamemap'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/terrain/builder.cpp:1137:29 in
../src/map/map.hpp:90:6: runtime error: member call on null pointer of type 'const gamemap *'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/map/map.hpp:90:6 in
AddressSanitizer:DEADLYSIGNAL
=================================================================
==4551==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00000513afed bp 0x7ffc135ca890 sp 0x7ffc135ca860 T0)
==4551==The signal is caused by a READ memory access.
==4551==Hint: address points to the zero page.
    #0 0x513afec in gamemap::w() const /home/matthias/vcs/github/wesnoth/build/../src/map/map.hpp:90:25
    #1 0x9591757 in terrain_builder::build_terrains() /home/matthias/vcs/github/wesnoth/build/../src/terrain/builder.cpp:1137:29
    #2 0x95965e8 in terrain_builder::rebuild_all() /home/matthias/vcs/github/wesnoth/build/../src/terrain/builder.cpp:392:2
    #3 0x9057441 in display::rebuild_all() /home/matthias/vcs/github/wesnoth/build/../src/display.cpp:419:12
    #4 0x9054bf9 in display::display(display_context const*, std::weak_ptr<wb::manager>, config const&, config const&, bool) /home/matthias/vcs/github/wesnoth/build/../src/display.cpp:171:2
    #5 0x654f0d8 in editor::editor_display::editor_display(editor::editor_controller&, config const&) /home/matthias/vcs/github/wesnoth/build/../src/editor/editor_display.cpp:33:4
    #6 0x6553ab3 in editor::editor_controller::editor_controller(config const&) /home/matthias/vcs/github/wesnoth/build/../src/editor/controller/editor_controller.cpp:71:13
    #7 0x642bd8f in editor::start(config const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/matthias/vcs/github/wesnoth/build/../src/editor/editor_main.cpp:36:21
    #8 0x50438b0 in game_launcher::start_editor(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/matthias/vcs/github/wesnoth/build/../src/game_launcher.cpp:1006:29
    #9 0x5043280 in game_launcher::goto_editor() /home/matthias/vcs/github/wesnoth/build/../src/game_launcher.cpp:758:7
    #10 0x4d0a60a in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /home/matthias/vcs/github/wesnoth/build/../src/wesnoth.cpp:831:12
    #11 0x4d04ef8 in main /home/matthias/vcs/github/wesnoth/build/../src/wesnoth.cpp:1150:19
    #12 0x7f33cb6e3f49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)
    #13 0x4c29029 in _start (/home/matthias/vcs/github/wesnoth/build/wesnoth+0x4c29029)
````

**Comment by Vultraz** [comment]
Known, will be a while before its fixed.

**Comment by matthiaskrgr** [comment]
The editor starts now but has no gui. :o

**Comment by Vultraz** [comment]
Deliberate :P I'm reworking the UIs.

**Comment by CelticMinstrel** [comment]
Suddenly thought that the editor palettes would be a great place to use the grid list box...
