### ISSUE TITLE
When on full screen mode, switching virtual desktops crashes the game

### ISSUE THREAD

**Issue by Gallaecio** [wesnoth/wesnoth#2880]
Switching to another virtual desktop and back crashes the game.

I wonder if it is related to #2690.

Reproduced running 1.14 (6a085e490f1798ec931b5c4a13266b6663c38869) on KDE Plasma 5.12.4 on Ubuntu with Kubuntu repositories.

Using `gdb`:

```
(gdb) run
Starting program: /home/adrian/castelao-20180212/home/adrian/proxectos/wesnoth/1.14/build/wesnoth 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe8426700 (LWP 18767)]
Battle for Wesnoth v1.13.13+dev (6a085e490f-Modified)
Started on Thu Apr 12 23:11:02 2018

Automatically found a possible data directory at /home/USER/castelao-20180212/home/USER/proxectos/wesnoth/1.14/build/..

Data directory:               /home/USER/castelao-20180212/home/USER/proxectos/wesnoth/1.14/build/..
User configuration directory: /home/USER/.config/wesnoth
User data directory:          /home/USER/.local/share/wesnoth/1.13
Cache directory:              /home/USER/.cache/wesnoth

[New Thread 0x7fffd4fd1700 (LWP 18768)]
[New Thread 0x7fffd4f90700 (LWP 18769)]
Setting mode to 1920x1080
[New Thread 0x7fffbe441700 (LWP 18770)]
[Thread 0x7fffbe441700 (LWP 18770) exited]
Checking lua scripts... ok

Thread 1 "wesnoth" received signal SIGSEGV, Segmentation fault.
0x00007ffff7b63944 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
(gdb) bt
#0  0x00007ffff7b63944 in  () at /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#1  0x000055555600bbf6 in sdl_copy_portion(surface const&, SDL_Rect*, surface&, SDL_Rect*) (screen=..., screen_rect=0x7fffffffbff0, dst=..., dst_rect=0x0) at /home/adrian/proxectos/wesnoth/1.14/src/sdl/utils.hpp:38
#2  0x0000555556635d16 in get_surface_portion(surface const&, SDL_Rect&) (src=..., area=...) at /home/adrian/proxectos/wesnoth/1.14/src/sdl/utils.cpp:2299
#3  0x0000555555ebba00 in gui2::canvas::blit(surface&, SDL_Rect) (this=0x555559cd1fa0, surf=..., rect=...) at /home/adrian/proxectos/wesnoth/1.14/src/gui/core/canvas.cpp:1445
#4  0x00005555566b36ec in gui2::panel::impl_draw_background(surface&, int, int) (this=0x55555a020150, frame_buffer=..., x_offset=0, y_offset=0) at /home/adrian/proxectos/wesnoth/1.14/src/gui/widgets/panel.cpp:71
#5  0x00005555559a6f8d in gui2::widget::draw_background(surface&, int, int) (this=0x55555a020150, frame_buffer=..., x_offset=0, y_offset=0) at /home/adrian/proxectos/wesnoth/1.14/src/gui/widgets/widget.cpp:380
#6  0x000055555596d5b7 in gui2::grid::impl_draw_children(surface&, int, int) (this=0x555557805e40, frame_buffer=..., x_offset=0, y_offset=0) at /home/adrian/proxectos/wesnoth/1.14/src/gui/widgets/grid.cpp:1022
#7  0x00005555559a70a9 in gui2::widget::draw_children(surface&, int, int) (this=0x555557805e40, frame_buffer=..., x_offset=0, y_offset=0) at /home/adrian/proxectos/wesnoth/1.14/src/gui/widgets/widget.cpp:395
#8  0x000055555675a7ca in gui2::generator<gui2::policy::minimum_selection::no_item, gui2::policy::maximum_selection::many_items, gui2::policy::placement::independent, gui2::policy::select_action::show>::impl_draw_children(surface&, int, int) (this=0x55555a110800, frame_buffer=..., x_offset=0, y_offset=0) at /home/adrian/proxectos/wesnoth/1.14/src/gui/widgets/generator_private.hpp:839
#9  0x00005555559a70a9 in gui2::widget::draw_children(surface&, int, int) (this=0x55555a110880, frame_buffer=..., x_offset=0, y_offset=0) at /home/adrian/proxectos/wesnoth/1.14/src/gui/widgets/widget.cpp:395
#10 0x000055555596d5cd in gui2::grid::impl_draw_children(surface&, int, int) (this=0x555559ee9df8, frame_buffer=..., x_offset=0, y_offset=0) at /home/adrian/proxectos/wesnoth/1.14/src/gui/widgets/grid.cpp:1023
#11 0x00005555559a70a9 in gui2::widget::draw_children(surface&, int, int) (this=0x555559ee9df8, frame_buffer=..., x_offset=0, y_offset=0) at /home/adrian/proxectos/wesnoth/1.14/src/gui/widgets/widget.cpp:395
#12 0x0000555555ff912e in gui2::container_base::impl_draw_children(surface&, int, int) (this=0x555559ee9a00, frame_buffer=..., x_offset=0, y_offset=0) at /home/adrian/proxectos/wesnoth/1.14/src/gui/widgets/container_base.cpp:204
#13 0x00005555559a70a9 in gui2::widget::draw_children(surface&, int, int) (this=0x555559ee9a00, frame_buffer=..., x_offset=0, y_offset=0) at /home/adrian/proxectos/wesnoth/1.14/src/gui/widgets/widget.cpp:395
#14 0x000055555596d5cd in gui2::grid::impl_draw_children(surface&, int, int) (this=0x555558aa71d8, frame_buffer=..., x_offset=0, y_offset=0) at /home/adrian/proxectos/wesnoth/1.14/src/gui/widgets/grid.cpp:1023
#15 0x00005555559a70a9 in gui2::widget::draw_children(surface&, int, int) (this=0x555558aa71d8, frame_buffer=..., x_offset=0, y_offset=0) at /home/adrian/proxectos/wesnoth/1.14/src/gui/widgets/widget.cpp:395
#16 0x0000555555ff912e in gui2::container_base::impl_draw_children(surface&, int, int) (this=0x555558aa6de0, frame_buffer=..., x_offset=0, y_offset=0) at /home/adrian/proxectos/wesnoth/1.14/src/gui/widgets/container_base.cpp:204
---Type <return> to continue, or q <return> to quit---

```

**Comment by Vultraz** [comment]
Odd, odd.... Probably means the framebuffer surface was replaced?

**Comment by jyrkive** [comment]
Which version of SDL are you using?

**Comment by Gallaecio** [comment]
```
adrian@curros:~$ dpkg -s libsdl2-dev | grep Version
Version: 2.0.6+dfsg1-3ubuntu1
```

**Comment by jyrkive** [comment]
OK. With SDL version that new, the newer codepath is used to deal with SDL surface reference counting (we update the refcount manually instead of calling the SDL functions for that).

**Comment by jyrkive** [comment]
Can't reproduce. The game survives changing virtual desktops just fine on my PC. Details about it:

* siduction GNU/Linux
* SDL 2.0.8
* KDE Plasma 5.12.4
* KDE Frameworks 5.44.0
* Nvidia GeForce GTX 1060 (driver 390.48)

**Comment by Gallaecio** [comment]
So you have SDL 2.0.8 and probaly SDL_image 2.0.3, while I have SDL 2.0.6 and SDL_image 2.0.1. SDL_image has received some security fixes, I wonder if it is related. I will try to report back once I get an upgraded version of those, unless someone else manages to reproduce the issue before that.

**Comment by shikadiqueen** [comment]
Can't reproduce here either using Debian sid with Plasma 5.12.4, Frameworks 5.44.0, Qt 5.10.1, SDL 2.0.8, and version 390.48 of the NVIDIA proprietary stack driving an NVIDIA GeForce GTX 1060 (6GB). ... So pretty much the same configuration as jyrkive, since siduction is built upon Sid.

What is your graphics hardware and driver, by the way? Have you checked KDE's bug tracker for any issues that may be related and specific to your configuration?

(Normally I'd be quick to blame Plasma (especially KWin) and NVIDIA's stack for having a well-known history of irreconcilable incompatibilities with each other.)

**Comment by Wedge009** [comment]
Fine for me also:

- Wesnoth 1.14.0+dev (aa772cbe)
- Kubuntu 17.10
- Plasma 5.12.4 / Frameworks 5.44.0
- Qt 5.9.1
- SDL 2.0.6

**Comment by Gallaecio** [comment]
Still happening, and I seem to have the same software as @Wedge009, so I guess the graphic cards (plural) may be responsible.

```
adrian@curros:~/proxectos/wesnoth/1.14/build$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
adrian@curros:~/proxectos/wesnoth/1.14/build$ dpkg -s libsdl2-dev | grep Version
Version: 2.0.6+dfsg1-3ubuntu1
adrian@curros:~/proxectos/wesnoth/1.14/build$ dpkg -s plasma-desktop | grep Version           
Version: 4:5.12.4-0ubuntu1~ubuntu17.10~ppa1
adrian@curros:~/proxectos/wesnoth/1.14/build$ dpkg -s plasma-framework | grep Version              
Version: 5.44.0-0ubuntu3~ubuntu17.10~ppa1
adrian@curros:~/proxectos/wesnoth/1.14/build$ sudo lshw -C display | grep GeForce
       product: GM107M [GeForce GTX 960M]
adrian@curros:~/proxectos/wesnoth/1.14/build$ sudo lshw -C display | grep 530
       product: HD Graphics 530
adrian@curros:~/proxectos/wesnoth/1.14/build$ dpkg -s nvidia-375 | grep Version
Version: 384.111-0ubuntu0.17.10.1
adrian@curros:~/proxectos/wesnoth/1.14/build$ dpkg -s libqt5core5a | grep Version
Version: 5.9.1+dfsg-10ubuntu1
adrian@curros:~/proxectos/wesnoth/1.14/build$ wesnoth
Battle for Wesnoth v1.14.0+dev (aa772cbe5d-Modified)
Started on Thu May  3 07:08:53 2018


Data directory:               /usr/local/share/wesnoth
User configuration directory: /home/USER/.config/wesnoth
User data directory:          /home/USER/.local/share/wesnoth/1.14
Cache directory:              /home/USER/.cache/wesnoth

Setting mode to 1920x1080
Checking lua scripts... ok
Segmentation fault (core dumped)
```

One of the ~10 times I executed wesnoth on the last test, with the aa772cb commit, I could not reproduce the issue, which has me even more puzzled.

**Comment by jvalrog** [comment]
It happens to me 100% of the time. This is xubuntu 17.10 with nvidia and sdl2 2.0

**Comment by Wedge009** [comment]
Trying this again, I still can't get anything to happen:
- Wesnoth 1.14.8+dev with SDL 2.0.9
- Kubuntu 19.04
- Plasma 5.16.4 / Frameworks 5.61.0
- Qt 5.12.2
- GTX 1080 Ti + GTX 980 Ti with NVIDIA 430.40 (for CUDA work)

**Comment by Wedge009** [comment]
@Gallaecio and @jvalrog When your Wesnoth crashes, are you using the 1.14 release? #4309 discusses a similar case albeit only with graphical bugs rather than a crash, and that report is for 1.15 development build.

**Comment by Gallaecio** [comment]
@Wedge009 I no longer have access to the laptop where I could reproduce this behavior. My current PC and laptop, neither of which has multiple graphic cards, cannot reproduce the issue.

**Comment by Wedge009** [comment]
Still not convinced multiple GPUs is a factor, but good to know you don't have it any more.

@jvalrog Are you still getting this issue? 100% of the time or not?

**Comment by Wedge009** [comment]
Given Gallaecio isn't encountering this any more and the lack of response from jvalrok, I'm closing this.
