### ISSUE TITLE
boost_unit_tests crash if launched in wrong directory

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#2933]
"build" is my build directory.
./build/boost_unit_tests works, however
````
cd build
./boost_unit_tests
````
crashes:
````
20180421 16:00:21 error filesystem: Trying to open file with empty name.
20180421 16:00:21 error preprocessor: Could not open file
20180421 16:00:21 error filesystem: Trying to open file with empty name.
20180421 16:00:21 error preprocessor: Could not open file
unknown location(0): fatal error: in "Test setup": unknown type
=================================================================
==32749==ERROR: AddressSanitizer: global-buffer-overflow on address 0x00000dc499a8 at pc 0x0000064c602e bp 0x7fff3b2d20b0 sp 0x7fff3b2d20a8
READ of size 8 at 0x00000dc499a8 thread T0
    #0 0x64c602d in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gui2::builder_window>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gui2::builder_window> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gui2::builder_window> > >::_M_begin() const /usr/lib64/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1/bits/stl_tree.h:743:29
    #1 0x64c5742 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gui2::builder_window>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gui2::builder_window> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gui2::builder_window> > >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /usr/lib64/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1/bits/stl_tree.h:2536:43
    #2 0x64a8417 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, gui2::builder_window, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gui2::builder_window> > >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /usr/lib64/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1/bits/stl_map.h:1189:21
    #3 0x649f0d7 in gui2::get_window_builder(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/matthias/vcs/github/wesnoth/build/../src/gui/core/gui_definition.cpp:276:30
    #4 0x644d567 in gui2::build_window_impl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/matthias/vcs/github/wesnoth/build/../src/gui/core/window_builder.cpp:85:56
    #5 0x641f006 in gui2::dialogs::modal_dialog::build_window() /home/matthias/vcs/github/wesnoth/build/../src/gui/dialogs/modal_dialog.cpp:219:12
    #6 0x641cdf4 in gui2::dialogs::modal_dialog::show(unsigned int) /home/matthias/vcs/github/wesnoth/build/../src/gui/dialogs/modal_dialog.cpp:75:2
    #7 0x63bad9f in gui2::dialogs::loading_screen::display(std::function<void ()>) /home/matthias/vcs/github/wesnoth/build/../src/gui/dialogs/loading_screen.cpp:220:21
    #8 0x5d904be in game_config_manager::load_game_config_with_loadscreen(game_config_manager::FORCE_RELOAD_CONFIG, game_classification const*) /home/matthias/vcs/github/wesnoth/build/../src/game_config_manager.cpp:138:2
    #9 0x5d8f4e3 in game_config_manager::init_game_config(game_config_manager::FORCE_RELOAD_CONFIG) /home/matthias/vcs/github/wesnoth/build/../src/game_config_manager.cpp:89:2
    #10 0x536a861 in mp_connect_fixture::mp_connect_fixture() /home/matthias/vcs/github/wesnoth/build/../src/tests/test_mp_connect.cpp:58:19
    #11 0x5369c04 in boost::unit_test::ut_detail::global_configuration_impl<mp_connect_fixture>::test_start(unsigned long) /usr/include/boost/test/tree/global_fixture.hpp:75:40
    #12 0x7f0238e56d6d in boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (/usr/lib/libboost_unit_test_framework.so.1.66.0+0x4cd6d)
    #13 0x7f0238e561a4 in boost::execution_monitor::catch_signals(boost::function<int ()> const&) (/usr/lib/libboost_unit_test_framework.so.1.66.0+0x4c1a4)
    #14 0x7f0238e56293 in boost::execution_monitor::execute(boost::function<int ()> const&) (/usr/lib/libboost_unit_test_framework.so.1.66.0+0x4c293)
    #15 0x7f0238e56a5e in boost::execution_monitor::vexecute(boost::function<void ()> const&) (/usr/lib/libboost_unit_test_framework.so.1.66.0+0x4ca5e)
    #16 0x7f0238e861f1 in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (/usr/lib/libboost_unit_test_framework.so.1.66.0+0x7c1f1)
    #17 0x7f0238e5a311 in boost::unit_test::framework::run(unsigned long, bool) (/usr/lib/libboost_unit_test_framework.so.1.66.0+0x50311)
    #18 0x7f0238e8390f in boost::unit_test::unit_test_main(bool (*)(), int, char**) (/usr/lib/libboost_unit_test_framework.so.1.66.0+0x7990f)
    #19 0x4f2cfd6 in main /usr/include/boost/test/unit_test.hpp:63:12
    #20 0x7f0238450f49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)
    #21 0x4ccb029 in _start (/home/matthias/vcs/github/wesnoth/build/boost_unit_tests+0x4ccb029)
0x00000dc499a8 is located 24 bytes to the left of global variable 'gui2::default_gui' defined in '../src/gui/core/gui_definition.cpp:30:27' (0xdc499c0) of size 8
0x00000dc499a8 is located 32 bytes to the right of global variable 'gui2::current_gui' defined in '../src/gui/core/gui_definition.cpp:29:27' (0xdc49980) of size 8
SUMMARY: AddressSanitizer: global-buffer-overflow /usr/lib64/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1/bits/stl_tree.h:743:29 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gui2::builder_window>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gui2::builder_window> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, gui2::builder_window> > >::_M_begin() const
Shadow bytes around the buggy address:
  0x000081b812e0: 01 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9
  0x000081b812f0: 01 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9
  0x000081b81300: 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9 01 f9 f9 f9
  0x000081b81310: f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9
  0x000081b81320: f9 f9 f9 f9 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9
=>0x000081b81330: 00 f9 f9 f9 f9[f9]f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x000081b81340: 00 00 f9 f9 f9 f9 f9 f9 00 00 00 00 f9 f9 f9 f9
  0x000081b81350: 00 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9
  0x000081b81360: 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9 01 f9 f9 f9
  0x000081b81370: f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9
  0x000081b81380: f9 f9 f9 f9 00 00 00 00 f9 f9 f9 f9 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==32749==ABORTING
````

**Comment by jyrkive** [comment]
Expected behavior.
