### ISSUE TITLE
possible to crash the game with the hotkey dialogue

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2953]
![hotkeys](https://user-images.githubusercontent.com/21158813/39126463-cb1ce2ac-4702-11e8-8fe9-fb0b6c87c66a.png)
When selecting the category "custom WML command", there is by default nothing in there. In all the other selections one has some items in the list, and one is marked.
Because there is none marked, pressing add / clear causes the game to crash.

Maybe hide the "custom WML command" category if it is empty?

Did I understand it correctly that the only way to add sth. there are add-ons?
What happens to the hotkey if you install such an add-on, add an hotkey for it, and remove it again?

Stacktrace:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000563c674cb2d3 in hotkey::get_hotkey_command(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()


#0  0x0000563c674cb2d3 in hotkey::get_hotkey_command(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#1  0x0000563c67330848 in gui2::dialogs::hotkey_bind::sdl_event_callback(gui2::window&, SDL_Event const&) ()
#2  0x0000563c66fdee2b in gui2::event::sdl_event_handler::handle_event(SDL_Event const&) ()
#3  0x0000563c675af91c in events::pump() ()
#4  0x0000563c6766e213 in gui2::window::show(bool, unsigned int) [clone .constprop.3402] ()
#5  0x0000563c6766e766 in gui2::dialogs::modal_dialog::show(unsigned int) [clone .constprop.3401] ()
#6  0x0000563c66ff0a97 in gui2::dialogs::preferences_dialog::add_hotkey_callback(gui2::listbox&) ()
#7  0x0000563c66f6cb6b in bool gui2::event::implementation::fire_event<std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&)>>(gui2::event::ui_event, std::vector<std::pair<gui2::widget*, gui2::event::ui_event>, std::allocator<std::pair<gui2::widget*, gui2::event::ui_event> > >&, gui2::widget*, gui2::widget*) ()
#8  0x0000563c66f6cefa in gui2::event::dispatcher::fire(gui2::event::ui_event, gui2::widget&) ()
#9  0x0000563c66fe0582 in gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >::mouse_button_click(gui2::widget*) ()
#10 0x0000563c66f6f928 in gui2::event::mouse_button<gui2::event::mouse_button_event_types_wrapper<(gui2::event::ui_event)8, (gui2::event::ui_event)9, (gui2::event::ui_event)10, (gui2::event::ui_event)11, (gui2::event::ui_event)12, (gui2::event::ui_event)13> >::signal_handler_sdl_button_up(gui2::event::ui_event, bool&, point const&) ()
#11 0x0000563c66f6ec93 in gui2::event::dispatcher::fire(gui2::event::ui_event, gui2::widget&, point const&) ()
#12 0x0000563c66fdf02d in gui2::event::sdl_event_handler::handle_event(SDL_Event const&) ()
#13 0x0000563c675af91c in events::pump() ()
#14 0x0000563c6766e213 in gui2::window::show(bool, unsigned int) [clone .constprop.3402] ()
#15 0x0000563c6766e766 in gui2::dialogs::modal_dialog::show(unsigned int) [clone .constprop.3401] ()
#16 0x0000563c66fa2272 in gui2::dialogs::preferences_dialog::display(config const&, preferences::PREFERENCE_VIEW) ()
#17 0x0000563c66fc63d5 in gui2::event::sdl_event_handler::hotkey_pressed(std::shared_ptr<hotkey::hotkey_base>) ()
#18 0x0000563c66fdde9a in gui2::event::sdl_event_handler::key_down(SDL_Event const&) ()
#19 0x0000563c66fdea87 in gui2::event::sdl_event_handler::handle_event(SDL_Event const&) ()
#20 0x0000563c675af91c in events::pump() ()
#21 0x0000563c6766e213 in gui2::window::show(bool, unsigned int) [clone .constprop.3402] ()
#22 0x0000563c6766e766 in gui2::dialogs::modal_dialog::show(unsigned int) [clone .constprop.3401] ()
#23 0x0000563c66f5ad8a in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#24 0x0000563c66e7503f in main ()
```

**Comment by CelticMinstrel** [comment]
Yeah, hiding it if there are no custom commands seems like the best option; but if that's too difficult then it should notice there are none and not try to select the non-existent first item.
