### ISSUE TITLE
wmllint crashes with unknown option

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3286]
An error message would be nicer than a crash.
```
Traceback (most recent call last):
  File "/home/space/git/wesnoth/data/tools/wmllint", line 3188, in <module>
    for fn in allcfgfiles(directory):
  File "/home/space/git/wesnoth/data/tools/wmllint", line 2933, in allcfgfiles
    if interesting(directory):
  File "/home/space/git/wesnoth/data/tools/wmllint", line 2927, in interesting
    return fn.endswith(".cfg") or is_map(fn) or issave(fn)
  File "/home/space/git/wesnoth/data/tools/wesnoth/wmltools3.py", line 268, in issave
    with codecs.open(filename, "r", "utf8") as content:
  File "/usr/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'clean'
```

**Comment by shikadiqueen** [comment]
So, without seeing the full command line you used, should we assume you accidentally ran something like `wmllint clean` instead of `wmllint --clean`, the tool assumed that was a directory to look into, didn't find it, and crashed in this way?
