### ISSUE TITLE
wmlindent crashes if file does not exist

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3346]
```
Traceback (most recent call last):
  File "/tmp/wesnoth/data/tools/wmlindent", line 323, in <module>
    arguments, "|".join(exclude))
  File "/tmp/wesnoth/data/tools/wmlindent", line 259, in convertor
    with codecs.open(filename,"r","utf8") as infp, codecs.open(filename + ".out", "w","utf8") as outfp:
  File "/usr/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'data/campaigns/tutorial/scenarios/01_Tutorial_part_2.cfg'
```

**Comment by Vultraz** [comment]
Under what circumstances could this arise? If you delete the file mid-run?

**Comment by sevu** [comment]
If the argument to wmlindent refers to an invalid location. Such as `wmlindent fwneöofnqwe.cfg`
