### ISSUE TITLE
Failed assertion in monte_carlo_combat_matrix::scale_probabilities()

### ISSUE THREAD

**Issue by edwardspec** [wesnoth/wesnoth#3650]
In Wesnoth v1.14.5, attached save file (requires an addon "Legend of the Invincibles") causes a failed assertion in `monte_carlo_combat_matrix::scale_probabilities()` after you click "End of turn".

[gladiators_crash.gz](https://github.com/wesnoth/wesnoth/files/2507134/gladiators_crash.gz)

Output:
```
$ wesnoth -l gladiators_crash.gz
Battle for Wesnoth v1.14.5
Started on Tue Oct 23 19:56:41 2018

Data directory:               /usr/share/wesnoth
User configuration directory: /home/USER/.config/wesnoth
User data directory:          /home/USER/.local/share/wesnoth/1.14
Cache directory:              /home/USER/.cache/wesnoth

Setting mode to 1366x690
Checking lua scripts... ok
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
20181023 19:56:52 error engine: failed to auto-store $second_unit at (-999,-999)
20181023 19:56:52 error engine: failed to auto-store $second_unit at (-999,-999)
20181023 19:56:52 error engine: failed to auto-store $second_unit at (-999,-999)
20181023 19:56:52 error engine: failed to auto-store $second_unit at (-999,-999)
20181023 19:56:52 error engine: failed to auto-store $second_unit at (-999,-999)
20181023 19:56:52 error engine: failed to auto-store $second_unit at (-999,-999)
20181023 19:56:52 error engine: failed to auto-store $second_unit at (-999,-999)
wesnoth: src/attack_prediction.cpp:1660: static void {anonymous}::monte_carlo_combat_matrix::scale_probabilities(const std::vector<double>&, std::vector<double>&, double, unsigned int): Assertion `std::abs(std::accumulate(target.begin(), target.end(), 0.0) - 1.0) < 0.001' failed.
```

GDB backtrace:
```
#0  0x00007ffff1068eab in raise () at /lib64/libc.so.6
#1  0x00007ffff10535b9 in abort () at /lib64/libc.so.6
#2  0x00007ffff1053491 in _nl_load_domain.cold.0 () at /lib64/libc.so.6
#3  0x00007ffff1061612 in  () at /lib64/libc.so.6
#4  0x0000555555dff5d9 in (anonymous namespace)::monte_carlo_combat_matrix::scale_probabilities(std::vector<double, std::allocator<double> > const&, std::vector<double, std::allocator<double> >&, double, unsigned int) (source=..., target=std::vector of length 184, capacity 256 = {...}, divisor=<optimized out>, singular_hp=<optimized out>) at src/attack_prediction.cpp:1654
#5  0x0000555555e011fe in (anonymous namespace)::monte_carlo_combat_matrix::monte_carlo_combat_matrix (b_initially_slowed_chance=0.99993438999999995, a_initially_slowed_chance=0, b_split=..., a_split=..., b_hit_chance=0.5, a_hit_chance=0.69999999999999996, rounds=<optimized out>, b_drain_constant=<optimized out>, a_drain_constant=<optimized out>, b_drain_percent=<optimized out>, a_drain_percent=<optimized out>, b_slow_damage=<optimized out>, a_slow_damage=7, b_damage=<optimized out>, a_damage=15, b_slows=<optimized out>, a_slows=<optimized out>, b_summary=..., a_summary=..., b_hp=146, a_hp=896, b_max_hp=<optimized out>, a_max_hp=<optimized out>, this=0x7fffd19ad170) at src/attack_prediction.cpp:1489
#6  0x0000555555e011fe in (anonymous namespace)::complex_fight((anonymous namespace)::attack_prediction_mode, battle_context_unit_stats const&, battle_context_unit_stats const&, unsigned int, unsigned int, std::array<std::vector<double, std::allocator<double> >, 2ul>&, std::array<std::vector<double, std::allocator<double> >, 2ul>&, double&, double&, bool, std::vector<(anonymous namespace)::combat_slice, std::allocator<(anonymous namespace)::combat_slice> >, std::vector<(anonymous namespace)::combat_slice, std::allocator<(anonymous namespace)::combat_slice> >, double, double) (mode=(anonymous namespace)::attack_prediction_mode::monte_carlo_simulation, stats=..., opp_stats=..., strikes=<optimized out>, opp_strikes=<optimized out>, summary=..., opp_summary=..., self_not_hit=@0x7fffffffb230: 1, opp_not_hit=@0x7fffffffb238: 1, levelup_considered=true, split=std::vector of length 1, capacity 1 = {...}, opp_split=std::vector of length 1, capacity 1 = {...}, initially_slowed_chance=0, opp_initially_slowed_chance=0.99993438999999995) at src/attack_prediction.cpp:2163
#7  0x0000555555e0458e in combatant::fight(combatant&, bool) (this=0x555557b8ef10, opponent=..., levelup_considered=true)
    at /usr/include/c++/8/new:169
#8  0x0000555555d6a7c3 in battle_context::get_attacker_combatant(combatant const*) () at src/actions/attack.cpp:455
#9  0x0000555555fda4df in ai::attack_analysis::analyze(gamemap const&, unit_map&, ai::readonly_context const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, double) (this=0x7fffffffbe00, map=..., units=..., ai_obj=..., dstsrc=..., srcdst=..., enemy_dstsrc=std::multimap with 0 elements, aggression=1)
    at src/ai/default/attack.cpp:141
#10 0x0000555555fd2c84 in ai::ai_default_rca::aspect_attacks_base::do_attack_analysis(map_location const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::array<map_location, 6ul> const&, bool*, std::vector<map_location, std::allocator<map
_location> >&, std::vector<ai::attack_analysis, std::allocator<ai::attack_analysis> >&, ai::attack_analysis&, team const&) const (this=0x555556d1afe0, loc=..., srcdst=std::multimap with 462 elements = {...}, dstsrc=std::multimap with 462 elements = {...}, fullmove_srcdst=std::multimap with 514 elements = {...}, fullmove_dstsrc=std::multimap with 514 elements = {...}, enemy_srcdst=..., enemy_dstsrc=..., tiles=..., used_locations=<optimized out>, units=..., result=..., cur_analysis=..., current_team=...) at src/ai/contexts.hpp:634
#11 0x0000555555fd2d15 in ai::ai_default_rca::aspect_attacks_base::do_attack_analysis(map_location const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::multimap<map_location, map_location, std::less<map_location>, std::allocator<std::pair<map_location const, map_location> > > const&, std::array<map_location, 6ul> const&, bool*, std::vector<map_location, std::allocator<map_location> >&, std::vector<ai::attack_analysis, std::allocator<ai::attack_analysis> >&, ai::attack_analysis&, team const&) const (this=0x555556d1afe0, loc=..., srcdst=std::multimap with 462 elements = {...}, dstsrc=std::multimap with 462 elements = {...}, fullmove_srcdst=std::multimap with 514 elements = {...}, fullmove_dstsrc=std::multimap with 514 elements = {...}, enemy_srcdst=..., enemy_dstsrc=..., tiles=..., used_locations=<optimized out>, units=..., result=..., cur_analysis=..., current_team=...) at src/ai/default/aspect_attacks.cpp:335
#12 0x0000555555fd571e in ai::ai_default_rca::aspect_attacks_base::analyze_targets() const (this=0x555556d1afe0)
    at src/units/unit.hpp:1177
#13 0x0000555555fd595a in ai::ai_default_rca::aspect_attacks_base::recalculate() const (this=0x555556d1afe0)
    at src/ai/default/aspect_attacks.cpp:69
#14 0x0000555555dcf9ac in ai::typesafe_aspect<std::vector<ai::attack_analysis, std::allocator<ai::attack_analysis> > >::get_ptr() const (this=0x555556d1afe0) at /usr/include/c++/8/ext/atomicity.h:98
#15 0x0000555555dd1ade in ai::composite_aspect<std::vector<ai::attack_analysis, std::allocator<ai::attack_analysis> > >::recalculate() const (this=0x555559b88f90) at src/ai/composite/aspect.hpp:301
#16 0x0000555555fc3367 in ai::typesafe_aspect<std::vector<ai::attack_analysis, std::allocator<ai::attack_analysis> > >::get_ptr() const (this=<optimized out>) at src/ai/contexts.cpp:571
#17 0x0000555555fc3367 in ai::typesafe_aspect<std::vector<ai::attack_analysis, std::allocator<ai::attack_analysis> > >::get() const (this=<optimized out>) at src/ai/composite/aspect.hpp:126
#18 0x0000555555fc3367 in ai::readonly_context_impl::get_attacks() const (this=<optimized out>) at src/ai/contexts.cpp:571
#19 0x0000555555fedb93 in ai::readonly_context_proxy::get_attacks() const (this=<optimized out>) at src/ai/contexts.hpp:671
#20 0x0000555555fedb93 in ai::ai_default_rca::combat_phase::evaluate() (this=0x5555577ee150) at src/ai/default/ca.cpp:169
#21 0x0000555556012614 in ai::ai_default_rca::candidate_action_evaluation_loop::do_play_stage() (this=0x555559681a70)
    at src/ai/default/stage_rca.cpp:112
#22 0x0000555555d9687c in ai::ai_composite::play_turn() (this=this@entry=0x555557a4e610) at src/ai/composite/ai.cpp:150
#23 0x0000555555dc8720 in ai::manager::play_turn(int) (this=0x7fffd5eacda8, side=6) at src/ai/manager.cpp:752
#24 0x0000555555f72cbb in playsingle_controller::play_ai_turn() (this=0x7fffffffc8b0) at src/play_controller.hpp:180
#25 0x0000555555f73271 in playsingle_controller::play_side_impl() (this=0x7fffffffc8b0) at src/playsingle_controller.cpp:390
#26 0x0000555555f6bfe5 in play_controller::play_side() (this=0x7fffffffc8b0) at src/play_controller.cpp:1168
#27 0x0000555555f6c9cf in play_controller::play_turn() (this=this@entry=0x7fffffffc8b0) at src/play_controller.cpp:1201
#28 0x0000555555f71fa8 in playsingle_controller::play_scenario_main_loop() (this=0x7fffffffc8b0) at src/playsingle_controller.cpp:175
#29 0x0000555555f74da3 in playsingle_controller::play_scenario(config const&) (this=0x7fffffffc8b0, level=...)
    at src/playsingle_controller.cpp:265
#30 0x0000555555e8e2db in campaign_controller::playmp_scenario(end_level_data&) (this=0x7fffffffcf50, end_level=...)
    at src/game_initialization/playcampaign.cpp:225
#31 0x0000555555e8ec25 in campaign_controller::play_game() (this=0x7fffffffcf50) at src/game_initialization/playcampaign.cpp:290
#32 0x0000555555aa78db in game_launcher::launch_game(game_launcher::RELOAD_GAME_DATA) (this=0x555556b34770, reload=<optimized out>)
    at src/game_launcher.cpp:983
#33 0x0000555555926a09 in do_gameloop (args=std::vector of length 3, capacity 4 = {...}) at src/wesnoth.cpp:844
#34 0x0000555555926a09 in main (argc=<optimized out>, argv=<optimized out>) at src/wesnoth.cpp:1153
#35 0x00007ffff105511b in __libc_start_main () at /lib64/libc.so.6
#36 0x0000555555960a7a in _start () at src/addon/info.cpp:232
```

**Comment by jyrkive** [comment]
For some reason, the AI is attempting to simulate a position where the Lich King is slowed with a probability of 99,993 %, yet the probability that its HP is 146 and it's not slowed is 9 %. That's obviously not possible, the "slowed" and "not slowed" probabilities combined can't exceed 100 %.

When calculating the HP distribution on the condition that the unit isn't slowed (in other words, scaling the "HP distribution if not slowed" list by the probability of not being slowed), the combined probability of all possibilities becomes 137 174 %. It's way out of allowed range, triggering the assertion.

I'll try to figure out where the mismatch between the slow probability and HP distribution originates.

**Comment by vgaming** [comment]
This happened for me as well today.

```
wesnoth: /build/wesnoth/src/wesnoth/src/attack_prediction.cpp:1660: static void {anonymous}::monte_carlo_combat_matrix::scale_probabilities(const std::vector<double>&, std::vector<double>&, double, unsigned int): Assertion `std::abs(std::accumulate(target.begin(), target.end(), 0.0) - 1.0) < 0.001' failed.
```

and wesnoth crashed in multiplayer game. There were many slowed units (and units having slowing weapons).

**Comment by vgaming** [comment]
@jyrkive thanks for fixing!
