### ISSUE TITLE
wmlxgettext crashes if there is no .cfg file to scan

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3719]
E.g.

```
$ ./wmlxgettext --directory=/tmp --recursive --domain=wesnoth -o out.pot
Traceback (most recent call last):
  File "./wmlxgettext", line 269, in <module>
    main()
  File "./wmlxgettext", line 213, in main
    for fileno, fx in enumerate(filelist):
TypeError: 'NoneType' object is not iterable
```
(happened to me when I was in the translation subdirectory)

**Comment by jostephd** [comment]
@sevu Try this please

```
diff --git a/data/tools/pywmlx/autof.py b/data/tools/pywmlx/autof.py
index f064f45d07a..51a87fb7a73 100644
--- a/data/tools/pywmlx/autof.py
+++ b/data/tools/pywmlx/autof.py
@@ -4,7 +4,7 @@ import re
 
 
 def autoscan(pathdir):
-    filelist = None
+    filelist = []
     parentdir = os.path.realpath(os.path.join(pathdir, '..'))
     for root, dirs, files in os.walk(pathdir, topdown=False):
         for name in files:
@@ -17,10 +17,7 @@ def autoscan(pathdir):
                     value = re.sub(r'^\/', '', value)
                 else:
                     value = re.sub(r'^(?:[A-Za-z]\:)?\\', '', value)
-                if filelist is None:
-                    filelist = [ value ]
-                else:
-                    filelist.append(value)
+                filelist.append(value)
                 # end if m
             # end for name
         # end for root
diff --git a/data/tools/wmlxgettext b/data/tools/wmlxgettext
index f5dfbe954ac..072fbb0041b 100755
--- a/data/tools/wmlxgettext
+++ b/data/tools/wmlxgettext
@@ -176,7 +176,6 @@ def main():
         fdebug = open('debug.txt', 'w', encoding='utf-8')
     pywmlx.statemachine.setup(sentlist, args.initdom, args.domain,
                               args.warnall, fdebug)
-    filelist = None
     if args.recursive is False and args.filelist is None:
         pywmlx.wmlerr("bad command line", "FILELIST must not be empty. "
                "Please, run wmlxgettext again and, this time, add some file "
```

**Comment by sevu** [comment]
It fixes it! Will you push it or shall I?

**Comment by jostephd** [comment]
Go ahead.
