### ISSUE TITLE
wesnoth_addon_manager crashes if not finding the add-on

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3727]
```
$ wesnoth/data/tools/wesnoth_addon_manager -u Addon_in_wrong_directory
Opening socket to add-ons.wesnoth.org:15014 for 1.14.x
Connected as 42.
Traceback (most recent call last):
  File "wesnoth/data/tools/wesnoth_addon_manager", line 320, in <module>
    with open(pbl_file_name, 'r') as pbl_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Addon_in_wrong_directory'
Closing socket.
```
That will happen if you call the program while not being in the data/add-ons directory with the -u option.

**Comment by jostephd** [comment]
Untested but I assume this would do it?

```
diff --git a/data/tools/wesnoth_addon_manager b/data/tools/wesnoth_addon_manager
index 3090601db6d..f3d368c56a1 100755
--- a/data/tools/wesnoth_addon_manager
+++ b/data/tools/wesnoth_addon_manager
@@ -294,7 +294,6 @@ if __name__ == "__main__":
         print_messages(data)
 
     elif args.upload:
-        cs = CampaignClient(address)
         if os.path.isdir(args.upload):
             # else basename returns an empty string
             args.upload = args.upload.rstrip("/")
@@ -358,6 +357,7 @@ if __name__ == "__main__":
                 "*.project",
                 "__MACOSX/"]
 
+        cs = CampaignClient(address)
         mythread = cs.put_campaign_async(name, cfgfile, wmldir, ign, pbl)
 
         pcounter = 0
```

**Comment by sevu** [comment]
Slightly different
```
$ wesnoth/data/tools/wesnoth_addon_manager -u Addon_in_wrong_directory
Traceback (most recent call last):
  File "wesnoth/data/tools/wesnoth_addon_manager", line 319, in <module>
    with open(pbl_file_name, 'r') as pbl_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Addon_in_wrong_directory'
```

**Comment by jostephd** [comment]
What did you expect to happen?

**Comment by sevu** [comment]
To not see the backtrace, only an error message.

**Comment by LovCAPONE** [comment]
I have made a [pull request](https://github.com/wesnoth/wesnoth/pull/3874) that might fix this issue. Here’s a snippet from the commit message:

>In the addon manager, there was no validation code for paths in the file system for uploading addons. This fix adds validation at the parsing level, so that the original code is left unchanged.
