### ISSUE TITLE
Typing ~ at the title screen segfaults

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3830]
On 1.14 only, typing `~` (tlide) at the title screen segfaults.

```
(gdb) bt
#0  0x0000555555eb6e48 in gui2::dialogs::lua_interpreter::display(lua_kernel_base*) ()
#1  0x0000555555a3c58e in gui2::event::dispatcher::execute_hotkey(hotkey::HOTKEY_COMMAND) ()
#2  0x0000555555a5031f in gui2::event::sdl_event_handler::key_down(SDL_Event const&) ()
#3  0x0000555555a4f47b in gui2::event::sdl_event_handler::handle_event(SDL_Event const&) ()
#4  0x00005555561c48be in events::pump() ()
#5  0x00005555559419d6 in gui2::window::show(bool, unsigned int) ()
#6  0x0000555555a6897d in gui2::dialogs::modal_dialog::show(unsigned int) ()
#7  0x000055555594c906 in main ()
```

The backtrace is from a release build because I don't have a debug build right now.

**Comment by jostephd** [comment]
Thanks, jyrkive. Indeed, cherry-picking that commit fixes the crash. @CelticMinstrel ?

**Comment by CelticMinstrel** [comment]
Looks fine to cherry-pick to 1.14.

**Comment by jostephd** [comment]
Backported in 21352b01e666e8ab935f85a4a3436c42c75c2dfe
