### ISSUE TITLE
Crash with units with invalid standing animations

### ISSUE THREAD

**Issue by shikadiqueen** [wesnoth/wesnoth#5032]
With Wesnoth 1.14, units with a defined standing animation that has a filter condition that can't be fulfilled may cause the game to crash with a segmentation fault due a null pointer dereference. This is probably platform-independent but it was reported to occur on Windows and I have confirmed it happens on Debian sid and on Wine as well.

One simple way to achieve the aforementioned scenario is to modify the Vampire Bat's WML, **removing all standing and movement animations** and leaving only this in their place:

```
    [standing_anim]
        start_time=0
        {STANDARD_IDLE_FILTER}
        [frame]
            image="units/undead/bat-se-[3~1,2~5,4].png:[50,60,80,60,50,60,80,60]"
        [/frame]
    [/standing_anim]
```

(The person who originally reported this issue on Discord was mistakenly using `{STANDARD_IDLE_FILTER}` in a standing unit animation, when it's actually meant to be used for idle animations. The WML contained in the macro includes the following filters that may cause the game to be unable to find a standing animation for the unit:

```
    # Poisoned units should have no idle animation.
    [filter]
        [not]
            status=poisoned
        [/not]
    [/filter]
    # Units next to enemies should not have idle animations
    [filter]
        [filter_adjacent]
            is_enemy="yes"
            count=0
        [/filter_adjacent]
    [/filter]
```

**Note:** By simply adding `{STANDARD_IDLE_FILTER}` to the Vampire Bat's existing directional standing animations instead of replacing them like above, some unusual behaviour can be observed that results in glitched animations being "left behind" by the unit when moved next to an enemy unit and away from it and back to it (etc.), but it doesn't actually crash the game.

## Steps to reproduce

* Modify the Vampire Bat's unit type WML in `data/core/units/bats/Bat_Vampire.cfg` as described above.
* Start A Tale of Two Brothers.
* Make sure standing unit animations are enabled in Preferences (this is the default).
* Use `:debug` to enable debug mode and create a Vampire Bat on the tile north of the enemy (blue) leader.
* The Vampire Bat will be invisible, but it still exists in the game and can be selected by clicking on the tile where it is supposed to be.
* Moving the subject away from the enemy leader will trigger a crash.

## Example backtrace

(Debian sid, using GCC 10.2.0, Boost 1.71, SDL 2.0.12. Note the null `this` pointer for the topmost stack frame.)

```
Thread 1 "wesnoth-debug" received signal SIGSEGV, Segmentation fault.
0x0000555555a9f870 in boost::intrusive_ptr<unit const>::operator-> (this=0x0) at /usr/include/boost/smart_ptr/intrusive_ptr.hpp:199
199             BOOST_ASSERT( px != 0 );
(gdb) bt
#0  0x0000555555a9f870 in boost::intrusive_ptr<unit const>::operator->() const (this=0x0) at /usr/include/boost/smart_ptr/intrusive_ptr.hpp:199
#1  0x0000555555e1e741 in unit_animator::get_animation_time_potential() const (this=0x7fffffffa460) at src/units/animation.cpp:1466
#2  0x0000555555e9f26b in move_unit_between(map_location const&, map_location const&, unit_ptr, unsigned int, unsigned int, unit_animator&, display&)
    (a=..., b=..., temp_unit=..., step_num=0, step_left=0, animator=..., disp=...) at src/units/udisplay.cpp:151
#3  0x0000555555ea05c1 in unit_display::unit_mover::proceed_to(boost::intrusive_ptr<unit>, unsigned long, bool, bool) (this=0x7fffffffa450, u=..., path_index=1, update=true, wait=false)
    at src/units/udisplay.cpp:362
#4  0x0000555555f61aea in actions::(anonymous namespace)::unit_mover::do_move(actions::(anonymous namespace)::unit_mover::route_iterator const&, actions::(anonymous namespace)::unit_mover::route_iterator const&, unit_display::unit_mover&) (this=0x7fffffffa960, step_from={x = 8, y = 2}, step_to={x = 8, y = 1}, animator=...) at src/actions/move.cpp:544
#5  0x0000555555f6374c in actions::(anonymous namespace)::unit_mover::try_actual_movement(bool) (this=0x7fffffffa960, show=true) at src/actions/move.cpp:989
#6  0x0000555555f64ef0 in actions::move_unit_internal(actions::undo_list*, bool, bool*, actions::(anonymous namespace)::unit_mover&)
    (undo_stack=0x7fffc45ce410, show_move=true, interrupted=0x7fffffffad4f, mover=...) at src/actions/move.cpp:1193
#7  0x0000555555f65a0b in actions::move_unit_and_record(std::vector<map_location, std::allocator<map_location> > const&, actions::undo_list*, bool, bool, bool*, actions::move_unit_spectator*)
    (steps=std::vector of length 2, capacity 2 = {...}, undo_stack=0x7fffc45ce410, continued_move=true, show_move=true, interrupted=0x7fffffffad4f, move_spectator=0x0)
    at src/actions/move.cpp:1279
#8  0x000055555626fac3 in events::mouse_handler::move_unit_along_route(std::vector<map_location, std::allocator<map_location> > const&, bool&) (this=
    0x7fffffffc360, steps=std::vector of length 2, capacity 2 = {...}, interrupted=@0x7fffffffad4f: false) at src/mouse_events.cpp:1202
#9  0x000055555626f5b9 in events::mouse_handler::move_unit_along_current_route() (this=0x7fffffffc360) at src/mouse_events.cpp:1147
#10 0x000055555626e281 in events::mouse_handler::move_action(bool) (this=0x7fffffffc360, browse=false) at src/mouse_events.cpp:1007
#11 0x000055555626d3e0 in events::mouse_handler::select_or_action(bool) (this=0x7fffffffc360, browse=false) at src/mouse_events.cpp:825
#12 0x0000555556453050 in play_controller::hotkey_handler::select_and_action() (this=0x55555c0a3090) at src/hotkey/hotkey_handler.cpp:122
#13 0x00005555566a6e5d in hotkey::command_executor::do_execute_command(hotkey::hotkey_command const&, int, bool, bool) (this=0x55555c0a3090, cmd=..., press=true, release=false)
    at src/hotkey/command_executor.cpp:332
#14 0x0000555556453ac2 in play_controller::hotkey_handler::do_execute_command(hotkey::hotkey_command const&, int, bool, bool) (this=0x55555c0a3090, cmd=..., index=-1, press=true, release=false)
    at src/hotkey/hotkey_handler.cpp:267
#15 0x00005555566a8349 in hotkey::command_executor::execute_command_wrap(hotkey::command_executor::queued_command const&) (this=0x55555c0a3090, command=...)
    at src/hotkey/command_executor.cpp:614
#16 0x00005555566a8780 in hotkey::command_executor::run_queued_commands() (this=0x55555c0a3090) at src/hotkey/command_executor.cpp:692
#17 0x00005555566a7f3f in hotkey::run_events(hotkey::command_executor*) (executor=0x55555c0a3090) at src/hotkey/command_executor.cpp:570
#18 0x00005555566a7e7a in hotkey::mbutton_event(SDL_Event const&, hotkey::command_executor*) (event=..., executor=0x55555c0a3090) at src/hotkey/command_executor.cpp:542
#19 0x000055555607ec24 in controller_base::handle_event(SDL_Event const&) (this=0x7fffffffc200, event=...) at src/controller_base.cpp:186
#20 0x00005555566765d4 in events::pump() () at src/events.cpp:746
```

**Comment by Wedge009** [comment]
Given 9de3ae1db9dd3d1a8deda4848724b9f74a21d232 is included from 1.17.15, is this still an issue in 1.18?
