### ISSUE TITLE
Improving unit placed events

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#5158]
Some tags fire as side-effect `unit placed` events.
That's due to implementation details, might be good to change that.

It's know to happen for:
- [x] move_unit, probably move_unit_fake too
- [x] unpetrify

are there more?

It's either due to the the Lua statement `u:extract()` or `u:to_map()`. Exists there an alternative which can be used?

<s>Edit: … could be as easy as `u:to_map(nil, nil, false)`</s>

Is as easy as `u:to_map(u.x, u.y, false)`

**Comment by CelticMinstrel** [comment]
I'm not 100% sure but I think calling `to_map()` on a unit that's already on the map might also not fire an event? So if the `extract()` isn't strictly necessary, removing it _might_ make a difference.

**Comment by sevu** [comment]
In the case of wesnoth.interface.move_unit_fake:
Without the extract the unit sprite remains until the unit reached it's goal and is removed then. But still fires an unit placed event.

For [unpetrify], without the extract() it causes a coredump, guess that's a bug by itself? The backtrace is with 1.15.5.

For other places I wonder why it is needed.

```
#0  std::__uniq_ptr_impl<unit_animation_component, std::default_delete<unit_animation_component> >::_M_ptr() const (this=0x548) at /usr/include/c++/10.2.0/bits/unique_ptr.h:173
#1  0x000056011ef77b8a in std::unique_ptr<unit_animation_component, std::default_delete<unit_animation_component> >::get() const (this=0x548) at /usr/include/c++/10.2.0/bits/unique_ptr.h:422
#2  0x000056011ef730ec in std::unique_ptr<unit_animation_component, std::default_delete<unit_animation_component> >::operator*() const (this=0x548) at /usr/include/c++/10.2.0/bits/unique_ptr.h:408
#3  0x000056011ef71c90 in unit::anim_comp() const (this=0x0) at src/units/unit.hpp:1532
#4  0x000056011ef5e5b9 in game_lua_kernel::intf_put_unit(lua_State*) (this=0x7f129c00fda0, L=0x7f129c010078) at src/scripting/game_lua_kernel.cpp:2184
#5  0x000056011ef76a8b in dispatch<&game_lua_kernel::intf_put_unit>(lua_State*) (L=0x7f129c010078) at src/scripting/game_lua_kernel.cpp:150
#6  0x000056011f7da10c in luaD_precall(lua_State*, lua_TValue*, int) (L=0x7f129c010078, func=0x7f129eef3730, nresults=0) at src/lua/ldo.cpp:434
#7  0x000056011f7f7bce in luaV_execute(lua_State*) (L=0x7f129c010078) at src/lua/lvm.cpp:1134
#8  0x000056011f7da4a1 in luaD_call(lua_State*, lua_TValue*, int) (L=0x7f129c010078, func=0x7f129eef35e0, nResults=0) at src/lua/ldo.cpp:499
#9  0x000056011f7da4ff in luaD_callnoyield(lua_State*, lua_TValue*, int) (L=0x7f129c010078, func=0x7f129eef35e0, nResults=0) at src/lua/ldo.cpp:509
#10 0x000056011f7d0a0e in f_call(lua_State*, void*) (L=0x7f129c010078, ud=0x7ffe7dcb6e00) at src/lua/lapi.cpp:943
#11 0x000056011f7d9378 in luaD_rawrunprotected(lua_State*, void (*)(lua_State*, void*), void*) (L=0x7f129c010078, f=0x56011f7d09d9 <f_call(lua_State*, void*)>, ud=0x7ffe7dcb6e00) at src/lua/ldo.cpp:142
#12 0x000056011f7dacfa in luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long) (L=0x7f129c010078, func=0x56011f7d09d9 <f_call(lua_State*, void*)>, u=0x7ffe7dcb6e00, old_top=32, ef=16) at src/lua/ldo.cpp:729
#13 0x000056011f7d0ae7 in lua_pcallk(lua_State*, int, int, int, long, int (*)(lua_State*, int, long)) (L=0x7f129c010078, nargs=1, nresults=0, errfunc=-3, ctx=0, k=0x0) at src/lua/lapi.cpp:969
#14 0x000056011ef8e6c0 in luaW_pcall_internal(lua_State*, int, int) (L=0x7f129c010078, nArgs=1, nRets=0) at src/scripting/lua_common.cpp:1020
#15 0x000056011ef8e747 in luaW_pcall(lua_State*, int, int, bool) (L=0x7f129c010078, nArgs=1, nRets=0, allow_wml_error=true) at src/scripting/lua_common.cpp:1036
#16 0x000056011ef6d184 in game_lua_kernel::run_wml_action(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, vconfig const&, game_events::queued_event const&) (this=0x7f129c00fda0, cmd="command", cfg=..., ev=...) at src/scripting/game_lua_kernel.cpp:4814
#17 0x000056011f6aa7c5 in game_events::event_handler::handle_event(game_events::queued_event const&, game_lua_kernel&) (this=0x560123c3dff0, event_info=..., lk=...) at src/game_events/handlers.cpp:73
#18 0x000056011f3b3c5a in game_events::wml_event_pump::process_event(std::shared_ptr<game_events::event_handler>&, game_events::queued_event const&) (this=0x7f129c523a50, handler_p=std::shared_ptr<game_events::event_handler> (use count 2, weak count 2) = {...}, ev=...) at src/game_events/pump.cpp:299
#19 0x000056011f3b4f97 in operator()(game_events::manager&, game_events::handler_ptr&) const (__closure=0x560124cb36f0, ptr=std::shared_ptr<game_events::event_handler> (use count 2, weak count 2) = {...}) at src/game_events/pump.cpp:584
#20 0x000056011f3b5f5b in std::__invoke_impl<void, game_events::wml_event_pump::operator()()::<lambda(game_events::manager&, game_events::handler_ptr&)>&, game_events::manager&, std::shared_ptr<game_events::event_handler>&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/10.2.0/bits/invoke.h:60
#21 0x000056011f3b5e23 in std::__invoke_r<void, game_events::wml_event_pump::operator()()::<lambda(game_events::manager&, game_events::handler_ptr&)>&, game_events::manager&, std::shared_ptr<game_events::event_handler>&>(struct {...} &) (__fn=...) at /usr/include/c++/10.2.0/bits/invoke.h:153
#22 0x000056011f3b5cd1 in std::_Function_handler<void(game_events::manager&, std::shared_ptr<game_events::event_handler>&), game_events::wml_event_pump::operator()()::<lambda(game_events::manager&, game_events::handler_ptr&)> >::_M_invoke(const std::_Any_data &, game_events::manager &, std::shared_ptr<game_events::event_handler> &) (__functor=..., __args#0=..., __args#1=std::shared_ptr<game_events::event_handler> (use count 2, weak count 2) = {...}) at /usr/include/c++/10.2.0/bits/std_function.h:291
#23 0x000056011f3a9d77 in std::function<void (game_events::manager&, std::shared_ptr<game_events::event_handler>&)>::operator()(game_events::manager&, std::shared_ptr<game_events::event_handler>&) const (this=0x7ffe7dcb76f0, __args#0=..., __args#1=std::shared_ptr<game_events::event_handler> (use count 2, weak count 2) = {...}) at /usr/include/c++/10.2.0/bits/std_function.h:622
#24 0x000056011f3a8fbb in game_events::manager::execute_on_events(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (game_events::manager&, std::shared_ptr<game_events::event_handler>&)>) (this=0x7f129ca1b5b0, event_id="turn_2_refresh", func=...) at src/game_events/manager.cpp:210
#25 0x000056011f3b577d in game_events::wml_event_pump::operator()() (this=0x7f129c523a50) at src/game_events/pump.cpp:580
#26 0x000056011f3b4d1d in game_events::wml_event_pump::fire(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, game_events::entity_location const&, game_events::entity_location const&, config const&) (this=0x7f129c523a50, event="turn_2_refresh", loc1=..., loc2=..., data=...) at src/game_events/pump.cpp:490
#27 0x000056011f52e61c in play_controller::do_init_side() (this=0x7ffe7dcb7fb0) at src/play_controller.cpp:526
#28 0x000056011f52dc75 in play_controller::maybe_do_init_side() (this=0x7ffe7dcb7fb0) at src/play_controller.cpp:461
#29 0x000056011f532d07 in play_controller::play_side() (this=0x7ffe7dcb7fb0) at src/play_controller.cpp:1174
#30 0x000056011f533113 in play_controller::play_turn() (this=0x7ffe7dcb7fb0) at src/play_controller.cpp:1225
#31 0x000056011f53e500 in playsingle_controller::play_scenario_main_loop() (this=0x7ffe7dcb7fb0) at src/playsingle_controller.cpp:171
#32 0x000056011f53edcb in playsingle_controller::play_scenario(config const&) (this=0x7ffe7dcb7fb0, level=...) at src/playsingle_controller.cpp:268
#33 0x000056011f3cfdcb in campaign_controller::playmp_scenario(end_level_data&) (this=0x7ffe7dcb86c0, end_level=...) at src/game_initialization/playcampaign.cpp:226
#34 0x000056011f3d0106 in campaign_controller::play_game() (this=0x7ffe7dcb86c0) at src/game_initialization/playcampaign.cpp:291
#35 0x000056011f3c41ef in (anonymous namespace)::enter_staging_mode((anonymous namespace)::mp_workflow_helper_ptr) (helper=std::shared_ptr<(anonymous namespace)::mp_workflow_helper> (use count 3, weak count 0) = {...}) at src/game_initialization/multiplayer.cpp:490
#36 0x000056011f3c45b4 in (anonymous namespace)::enter_create_mode((anonymous namespace)::mp_workflow_helper_ptr) (helper=std::shared_ptr<(anonymous namespace)::mp_workflow_helper> (use count 3, weak count 0) = {...}) at src/game_initialization/multiplayer.cpp:516
#37 0x000056011f3c583f in mp::start_local_game(game_config_view const&, saved_game&) (game_config=..., state=...) at src/game_initialization/multiplayer.cpp:689
#38 0x000056011ecaa96f in game_launcher::play_multiplayer(game_launcher::mp_selection) (this=0x56012136cb80, res=game_launcher::MP_LOCAL) at src/game_launcher.cpp:894
#39 0x000056011eb23763 in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (args=std::vector of length 2, capacity 2 = {...}) at src/wesnoth.cpp:923
#40 0x000056011eb2403b in main(int, char**) (argc=2, argv=0x7ffe7dcb9fe8) at src/wesnoth.cpp:1142
```
