### ISSUE TITLE
Mandatory widget leader_image hasn't been defined

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5648]
To reproduce on 1.15.11, choose the Wilderlands map in scenario selection, then assign side 2 and side 3 to team 1.  On assigning side 3, the below error will appear:
![unknown](https://user-images.githubusercontent.com/3030250/113025512-a57eec00-914d-11eb-946d-8894d58ed419.png)

**Comment by Pentarctagon** [comment]
As of current master (a2c795bfd7a22c6196f2b5bd1386edaf1523e541) this now crashes with the error `double free or corruption (out)`.

**Comment by Pentarctagon** [comment]
Backtrace:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff709c859 in __GI_abort () at abort.c:79
#2  0x00007ffff71073ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7231285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff710f47c in malloc_printerr (str=str@entry=0x7ffff7233670 "double free or corruption (out)") at malloc.c:5347
#4  0x00007ffff7111120 in _int_free (av=0x7ffff7262b80 <main_arena>, p=0x555557ae69f0, have_lock=<optimized out>) at malloc.c:4314
#5  0x0000555555de5918 in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<help::unit_topic_generator, std::allocator<help::unit_topic_generator>, (__gnu_cxx::_Lock_policy)2> >::deallocate(std::_Sp_counted_ptr_inplace<help::unit_topic_generator, std::allocator<help::unit_topic_generator>, (__gnu_cxx::_Lock_policy)2>*, unsigned long) (this=0x7fffffffb52f, __p=0x555557ae6a00) at /usr/include/c++/9/ext/new_allocator.h:128
#6  0x0000555555de4aad in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<help::unit_topic_generator, std::allocator<help::unit_topic_generator>, (__gnu_cxx::_Lock_policy)2> > >::deallocate(std::allocator<std::_Sp_counted_ptr_inplace<help::unit_topic_generator, std::allocator<help::unit_topic_generator>, (__gnu_cxx::_Lock_policy)2> >&, std::_Sp_counted_ptr_inplace<help::unit_topic_generator, std::allocator<help::unit_topic_generator>, (__gnu_cxx::_Lock_policy)2>*, unsigned long) (__a=..., __p=0x555557ae6a00, __n=1) at /usr/include/c++/9/bits/alloc_traits.h:470
#7  0x0000555555de349c in std::__allocated_ptr<std::allocator<std::_Sp_counted_ptr_inplace<help::unit_topic_generator, std::allocator<help::unit_topic_generator>, (__gnu_cxx::_Lock_policy)2> > >::~__allocated_ptr()
    (this=0x7fffffffb530, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/allocated_ptr.h:73
#8  0x0000555555de633e in std::_Sp_counted_ptr_inplace<help::unit_topic_generator, std::allocator<help::unit_topic_generator>, (__gnu_cxx::_Lock_policy)2>::_M_destroy() (this=0x555557ae6a00)
    at /usr/include/c++/9/bits/shared_ptr_base.h:565
#9  0x0000555555bc3394 in gui2::find_widget<gui2::drawing>(utils::const_clone<gui2::widget, gui2::drawing>::pointer, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool) (widget=
    0x555557ae6a00, id="leader_image", must_be_active=false, must_exist=true) at src/gui/auxiliary/find_widget.hpp:73
#10 0x0000555555c3ae4c in gui2::find_widget<gui2::drawing>(utils::const_clone<gui2::widget, gui2::drawing>::pointer, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
    (widget=0x555557ae6a00, id="leader_image", must_be_active=false) at src/gui/auxiliary/find_widget.hpp:99
#11 0x0000555555c35fde in gui2::dialogs::mp_staging::update_leader_display(std::shared_ptr<ng::side_engine>, gui2::grid&) (this=0x7fffffffc270, side=std::shared_ptr<class ng::side_engine> (use count 4, weak count 0) = {...}, 
    row_grid=...) at src/gui/dialogs/multiplayer/mp_staging.cpp:485
#12 0x0000555555c36d25 in gui2::dialogs::mp_staging::network_handler() (this=0x7fffffffc270) at src/gui/dialogs/multiplayer/mp_staging.cpp:548
#13 0x0000555555c416da in std::__invoke_impl<void, void (gui2::dialogs::mp_staging::*&)(), gui2::dialogs::mp_staging*&>(std::__invoke_memfun_deref, void (gui2::dialogs::mp_staging::*&)(), gui2::dialogs::mp_staging*&)
    (__f=@0x55555b3d72b0: (void (gui2::dialogs::mp_staging::*)(class gui2::dialogs::mp_staging * const)) 0x555555c36a66 <gui2::dialogs::mp_staging::network_handler()>, __t=@0x55555b3d72c0: 0x7fffffffc270)
    at /usr/include/c++/9/bits/invoke.h:73
#14 0x0000555555c40a3f in std::__invoke<void (gui2::dialogs::mp_staging::*&)(), gui2::dialogs::mp_staging*&>(void (gui2::dialogs::mp_staging::*&)(), gui2::dialogs::mp_staging*&)
    (__fn=@0x55555b3d72b0: (void (gui2::dialogs::mp_staging::*)(class gui2::dialogs::mp_staging * const)) 0x555555c36a66 <gui2::dialogs::mp_staging::network_handler()>) at /usr/include/c++/9/bits/invoke.h:95
#15 0x0000555555c3f5c5 in std::_Bind<void (gui2::dialogs::mp_staging::*(gui2::dialogs::mp_staging*))()>::__call<void, unsigned long&&, 0ul>(std::tuple<unsigned long&&>&&, std::_Index_tuple<0ul>) (this=0x55555b3d72b0, __args=...)
    at /usr/include/c++/9/functional:400
#16 0x0000555555c3d596 in std::_Bind<void (gui2::dialogs::mp_staging::*(gui2::dialogs::mp_staging*))()>::operator()<unsigned long, void>(unsigned long&&) (this=0x55555b3d72b0) at /usr/include/c++/9/functional:484
#17 0x0000555555c3b396 in std::_Function_handler<void (unsigned long), std::_Bind<void (gui2::dialogs::mp_staging::*(gui2::dialogs::mp_staging*))()> >::_M_invoke(std::_Any_data const&, unsigned long&&)
    (__functor=..., __args#0=@0x7fffffffbb20: 37) at /usr/include/c++/9/bits/std_function.h:300
#18 0x0000555555ba268b in std::function<void (unsigned long)>::operator()(unsigned long) const (this=0x7fffffffbb80, __args#0=37) at /usr/include/c++/9/bits/std_function.h:688
#19 0x0000555555ba21a3 in gui2::execute_timer(unsigned long) (id=37) at src/gui/core/timer.cpp:221
#20 0x0000555555b981b0 in gui2::event::sdl_event_handler::handle_event(SDL_Event const&) (this=0x555557ca0be0, event=...) at src/gui/core/event/handler.cpp:428
#21 0x00005555569003e5 in events::pump() () at src/events.cpp:739
#22 0x000055555597cdf2 in gui2::window::show(bool, unsigned int) (this=0x555557e00a50, restore=false, auto_close_timeout=0) at src/gui/widgets/window.cpp:540
#23 0x0000555555bccf6e in gui2::dialogs::modal_dialog::show(unsigned int) (this=0x7fffffffc270, auto_close_time=0) at src/gui/dialogs/modal_dialog.cpp:89
#24 0x0000555555b45bce in gui2::dialogs::mp_staging::execute<ng::connect_engine&, wesnothd_connection*>(ng::connect_engine&, wesnothd_connection*&&) () at src/gui/dialogs/multiplayer/mp_staging.hpp:45
#25 0x0000555555b3ef67 in mp::(anonymous namespace)::mp_manager::enter_staging_mode() (this=0x7fffffffc970) at src/game_initialization/multiplayer.cpp:637
#26 0x0000555555b3ec16 in mp::(anonymous namespace)::mp_manager::enter_create_mode() (this=0x7fffffffc970) at src/game_initialization/multiplayer.cpp:615
#27 0x0000555555b3fb63 in mp::start_local_game() () at src/game_initialization/multiplayer.cpp:730
#28 0x0000555555b56873 in game_launcher::play_multiplayer(game_launcher::mp_mode) (this=0x5555575b1940, mode=game_launcher::mp_mode::LOCAL) at src/game_launcher.cpp:866
#29 0x000055555599e7b7 in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
    (args=std::vector of length 1, capacity 1 = {...}) at src/wesnoth.cpp:915
#30 0x000055555599f196 in main(int, char**) (argc=1, argv=0x7fffffffe5f8) at src/wesnoth.cpp:1093=
```

**Comment by Pentarctagon** [comment]
According to git bisect, the bad commit is 8edeb2310828409d5e9cd06d6d0d9b04dee48233.
