### ISSUE TITLE
Assert on loading a game with a unit whose `[illuminates]` ability uses a time-of-day based filter

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#6340]
### Game and System Information
- 1.16.1+dev, originally reported by Konrad [in Discord](https://discord.com/channels/231976805987385345/259976436490829825/914837067442319410)
- add-on The Wolves Last Path version 0.1.3

### Describe the bug
The game asserts on loading a mid-game save (which Github is currently not wanting to attach, so get the file from Discord). Editing the save-game to remove the "Ring of light and darkness" `[object]` prevents the assert.

That ring gives the unit an `[illuminates]` ability which uses a time-of-day based filter. In evaluating this, the `tod_manager::get_illuminated_time_of_day` function calls `unit::get_abilities` which then attempts to get the unit map via `display`, and `display::get_singleton()` asserts.

The unit_map is passed as an argument to `tod_manager::get_illuminated_time_of_day`, but isn't passed as an argument further down the stack.

```
#define ABILITY_FLUORESCENCE
    [illuminates]
        id=fluorescence
        value=-25
        max_value=-25
        min_value = 25
        cumulative=no
        name= _ "Fluorescence"
        female_name= _ "female^fluorescence"
        description= _ "This unit darkens the surrounding area by night and illuminates it by day. This is mostly useless, except at dawn and at dusk, when it retains the same illumination of the previous turn, and for times with bonuses lower then 25%."
        affect_self=yes
        [filter_self]
            [filter_location]
                time_of_day_id=dawn,dawn_hour,first_watch,midnight,second_watch,underground
                [or]
                    time_of_day=chaotic
                [/or]
            [/filter_location]
        [/filter_self]
    [/illuminates]
    [illuminates]        
        id=fluorescence
        value=25
        max_value=25
        min_value = -25
        cumulative=no
        affect_self=yes
        [filter_self]
            [filter_location]
                time_of_day_id=morning,midday,afternoon,dusk,dusk_hour
                [or]
                    time_of_day=lawful
                [/or]
            [/filter_location]
        [/filter_self]
    [/illuminates]
#enddef
```

Call stack:
```
#3  0x00007ffff6fef7f2 in __GI___assert_fail
    (assertion=0x555556b1d684 "display::get_singleton()", file=0x555556b1d640 "src/units/abilities.cpp", line=200, function=0x555556b1d6a0 "unit_ability_list unit::get_abilities(const string&, const map_location&) const") at assert.c:101
#4  0x00005555560fdc71 in unit::get_abilities(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, map_location const&) const
    (this=0x7fffa9add620, tag_name="illuminates", loc=...) at src/units/abilities.cpp:200
#5  0x0000555555f7a3f3 in unit::get_abilities(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
    (this=0x7fffa9add620, tag_name="illuminates") at src/units/unit.hpp:1702
#6  0x00005555560f60bc in tod_manager::get_illuminated_time_of_day(unit_map const&, gamemap const&, map_location const&, int) const (this=0x7fffa98ee060, units=..., 
    map=..., loc=..., for_turn=0) at src/tod_manager.cpp:242
#7  0x00005555560e28cf in terrain_filter::match_internal(map_location const&, unit const*, bool) const (this=0x7fffdb78ec20, loc=..., ref_unit=0x0, ignore_xy=false)
    at src/terrain/filter.cpp:272
#8  0x00005555560e4e43 in terrain_filter::match_impl(map_location const&, unit const*) const (this=0x7fffdb78ec20, loc=..., ref_unit=0x0)
    at src/terrain/filter.cpp:413
#9  0x00005555560231cc in terrain_filter::match(map_location const&) const (this=0x7fffdb78ec20, loc=...)
    at src/terrain/filter.hpp:44
#10 0x000055555616062e in operator()(vconfig const&, unit_filter_impl::unit_filter_args const&) const (__closure=0x7fffa9b59bf8, c=..., args=...)
    at src/units/filter.cpp:801
#11 0x000055555618539f in (anonymous namespace)::unit_filter_child_literal<unit_filter_impl::unit_filter_compound::fill(vconfig)::<lambda(const vconfig&, const unit_filter_impl::unit_filter_args&)> >::matches(const unit_filter_impl::unit_filter_args &) const (this=0x7fffa9b59bd0, args=...)
    at src/units/filter.cpp:170
#12 0x000055555615bb89 in unit_filter_impl::unit_filter_compound::filter_impl(unit_filter_impl::unit_filter_args const&) const (this=0x7fffdb78f0b0, args=...)
    at src/units/filter.cpp:271
#13 0x000055555615b8af in unit_filter_impl::unit_filter_compound::matches(unit_filter_impl::unit_filter_args const&) const (this=0x7fffdb78f0b0, args=...)
    at src/units/filter.cpp:244
#14 0x0000555556021d96 in unit_filter::matches(unit const&, map_location const&) const (this=0x7fffdb78f080, u=..., loc=...)
    at src/units/filter.hpp:133
#15 0x00005555561db3b2 in unit::add_modification(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, config const&, bool)
    (this=0x7fffa9b395c0, mod_type="object", mod=..., no_add=true) at src/units/unit.cpp:2251
(gdb) p mod.debug()
$1 = "description = This ring allows its bearer to illuminate at day and darken at night (it doesn't work indoors)\nimage = items/ring-brown.png\nname = Ring of light and darkness\n[effect]\n\tapply_to = new_abi"...
#16 0x00005555561dc8d8 in unit::apply_modifications() (this=0x7fffa9b395c0) at src/units/unit.cpp:2402
#17 0x00005555561cfb4f in unit::advance_to(unit_type const&, bool) (this=0x7fffa9b395c0, u_type=..., use_traits=true)
    at src/units/unit.cpp:946
#18 0x00005555561cb56b in unit::init(config const&, bool, vconfig const*) (this=0x7fffa9b395c0, cfg=..., use_traits=true, vcfg=0x0)
    at src/units/unit.cpp:438
#19 0x000055555602328e in unit::create(config const&, bool, vconfig const*) (cfg=..., use_traits=true, vcfg=0x0)
    at src/units/unit.hpp:193
#20 0x0000555556854ea2 in unit_creator::add_unit(config const&, vconfig const*) (this=0x7fffdb78fcb0, cfg=..., vcfg=0x0)
    at src/actions/unit_creator.cpp:186
#21 0x000055555680d4bb in team_builder::place_units() (this=0x7fffa99ff370) at src/teambuilder.cpp:261
```

**Comment by stevecotton** [comment]
Oops, yes it is.
