### ISSUE TITLE
achivements: runtime error

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#7929]
### Game and System Information

- **Version:** ea98e42c1bd5e933bcb3769cbb4e4c00a69aa653
- **Downloaded from:**
- **Build info:** 
- **OS:** manjaro 

### Description of the bug
```
Battle for Wesnoth v1.17.21+dev x86_64
Started on Sun Oct  1 01:40:49 2023

Automatically found a possible data directory at: /home/USER/vcs/github/wesnoth/build/..

Data directory:               /home/USER/vcs/github/wesnoth/build/..
User configuration directory: /home/USER/.config/wesnoth
User data directory:          /home/USER/.local/share/wesnoth/1.17
Cache directory:              /home/USER/.cache/wesnoth


Setting mode to 1250x1044
Checking lua scripts... ok
/home/matthias/vcs/github/wesnoth/src/gui/dialogs/achievements_dialog.cpp:165:3: runtime error: downcast of address 0x619000349e80 which does not point to an object of type 'image'
0x619000349e80: note: object is of type 'gui2::drawing'
 00 00 00 00  10 61 63 f2 36 56 00 00  00 00 00 00 be be be be  70 62 63 f2 36 56 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'gui2::drawing'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/matthias/vcs/github/wesnoth/src/gui/dialogs/achievements_dialog.cpp:165:3 in
```

### Steps to reproduce the behavior

1) click "achivements" button

**Comment by matthiaskrgr** [comment]
```
/home/matthias/vcs/github/wesnoth/src/gui/dialogs/achievements_dialog.cpp:165:3: runtime error: downcast of address 0x6190002e2c80 which does not point to an object of type 'image'
0x6190002e2c80: note: object is of type 'gui2::drawing'
 00 00 00 00  10 d1 2e 24 e2 55 00 00  00 00 00 00 be be be be  70 d2 2e 24 e2 55 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'gui2::drawing'
    #0 0x55e222c127b0 in gui2::dialogs::achievements_dialog::set_sub_achievements(gui2::grid&, achievement const&) /home/matthias/vcs/github/wesnoth/src/gui/dialogs/achievements_dialog.cpp:165:3
    #1 0x55e222c0f9fd in gui2::dialogs::achievements_dialog::set_achievements_row() /home/matthias/vcs/github/wesnoth/src/gui/dialogs/achievements_dialog.cpp:134:3
    #2 0x55e222c0d005 in gui2::dialogs::achievements_dialog::pre_show(gui2::window&) /home/matthias/vcs/github/wesnoth/src/gui/dialogs/achievements_dialog.cpp:74:3
    #3 0x55e222a27692 in gui2::dialogs::modal_dialog::show(unsigned int) /home/matthias/vcs/github/wesnoth/src/gui/dialogs/modal_dialog.cpp:87:2
    #4 0x55e222bfd99b in gui2::dialogs::title_screen::show_achievements() /home/matthias/vcs/github/wesnoth/src/gui/dialogs/title_screen.cpp:468:6
    #5 0x55e222c09ab1 in void std::__invoke_impl<void, void (gui2::dialogs::title_screen::*&)(), gui2::dialogs::title_screen*&>(std::__invoke_memfun_deref, void (gui2::dialogs::title_screen::*&)(), gui2::dialogs::title_screen*&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/invoke.h:74:14
    #6 0x55e222c09ab1 in std::__invoke_result<void (gui2::dialogs::title_screen::*&)(), gui2::dialogs::title_screen*&>::type std::__invoke<void (gui2::dialogs::title_screen::*&)(), gui2::dialogs::title_screen*&>(void (gui2::dialogs::title_screen::*&)(), gui2::dialogs::title_screen*&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/invoke.h:96:14
    #7 0x55e222c09ab1 in void std::_Bind<void (gui2::dialogs::title_screen::* (gui2::dialogs::title_screen*))()>::__call<void, 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/functional:506:11
    #8 0x55e222c09ab1 in void std::_Bind<void (gui2::dialogs::title_screen::* (gui2::dialogs::title_screen*))()>::operator()<void>() /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/functional:591:17
    #9 0x55e222c09ab1 in void std::__invoke_impl<void, std::_Bind<void (gui2::dialogs::title_screen::* (gui2::dialogs::title_screen*))()>&>(std::__invoke_other, std::_Bind<void (gui2::dialogs::title_screen::* (gui2::dialogs::title_screen*))()>&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/invoke.h:61:14
    #10 0x55e222c09ab1 in std::enable_if<is_invocable_r_v<void, std::_Bind<void (gui2::dialogs::title_screen::* (gui2::dialogs::title_screen*))()>&>, void>::type std::__invoke_r<void, std::_Bind<void (gui2::dialogs::title_screen::* (gui2::dialogs::title_screen*))()>&>(std::_Bind<void (gui2::dialogs::title_screen::* (gui2::dialogs::title_screen*))()>&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/invoke.h:111:2
    #11 0x55e222c09ab1 in std::_Function_handler<void (), std::_Bind<void (gui2::dialogs::title_screen::* (gui2::dialogs::title_screen*))()>>::_M_invoke(std::_Any_data const&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/std_function.h:290:9
    #12 0x55e222c07a29 in std::function<void ()>::operator()() const /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/std_function.h:591:9
    #13 0x55e222c07a29 in void std::__invoke_impl<void, std::function<void ()>&>(std::__invoke_other, std::function<void ()>&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/invoke.h:61:14
    #14 0x55e222c07a29 in std::__invoke_result<std::function<void ()>&>::type std::__invoke<std::function<void ()>&>(std::function<void ()>&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/invoke.h:96:14
    #15 0x55e222c07a29 in void std::_Bind<std::function<void ()> ()>::__call<void, gui2::widget&, gui2::event::ui_event&&, bool&, bool&>(std::tuple<gui2::widget&, gui2::event::ui_event&&, bool&, bool&>&&, std::_Index_tuple<>) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/functional:506:11
    #16 0x55e222c07a29 in void std::_Bind<std::function<void ()> ()>::operator()<gui2::widget&, gui2::event::ui_event, bool&, bool&, void>(gui2::widget&, gui2::event::ui_event&&, bool&, bool&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/functional:591:17
    #17 0x55e222c07a29 in void std::__invoke_impl<void, std::_Bind<std::function<void ()> ()>&, gui2::widget&, gui2::event::ui_event, bool&, bool&>(std::__invoke_other, std::_Bind<std::function<void ()> ()>&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/invoke.h:61:14
    #18 0x55e222c07a29 in std::enable_if<is_invocable_r_v<void, std::_Bind<std::function<void ()> ()>&, gui2::widget&, gui2::event::ui_event, bool&, bool&>, void>::type std::__invoke_r<void, std::_Bind<std::function<void ()> ()>&, gui2::widget&, gui2::event::ui_event, bool&, bool&>(std::_Bind<std::function<void ()> ()>&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/invoke.h:111:2
    #19 0x55e222c07a29 in std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&), std::_Bind<std::function<void ()> ()>>::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/std_function.h:290:9
    #20 0x55e2227f302e in std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&)>::operator()(gui2::widget&, gui2::event::ui_event, bool&, bool&) const /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/std_function.h:591:9
    #21 0x55e2227f302e in bool gui2::event::implementation::fire_event<(gui2::event::event_category)256>(gui2::event::ui_event, std::vector<std::pair<gui2::widget*, gui2::event::ui_event>, std::allocator<std::pair<gui2::widget*, gui2::event::ui_event>>> const&, gui2::widget*, gui2::widget*) /home/matthias/vcs/github/wesnoth/src/gui/core/event/dispatcher_private.hpp:262:4
    #22 0x55e2227e3f9c in bool gui2::event::fire_event<(gui2::event::event_category)256>(gui2::event::ui_event, gui2::event::dispatcher*, gui2::widget*) /home/matthias/vcs/github/wesnoth/src/gui/core/event/dispatcher_private.hpp:332:9
    #23 0x55e2227e01f7 in gui2::event::dispatcher::fire(gui2::event::ui_event, gui2::widget&) /home/matthias/vcs/github/wesnoth/src/gui/core/event/dispatcher.cpp:93:10
    #24 0x55e22282a4d0 in gui2::event::mouse_button<0ul>::mouse_button_click(gui2::widget*) /home/matthias/vcs/github/wesnoth/src/gui/core/event/distributor.cpp:567:10
    #25 0x55e222828698 in gui2::event::mouse_button<0ul>::signal_handler_sdl_button_up(gui2::event::ui_event, bool&, point const&) /home/matthias/vcs/github/wesnoth/src/gui/core/event/distributor.cpp:538:4
    #26 0x55e22282957d in void std::__invoke_impl<void, void (gui2::event::mouse_button<0ul>::*&)(gui2::event::ui_event, bool&, point const&), gui2::event::mouse_button<0ul>*&, gui2::event::ui_event, bool&, point const&>(std::__invoke_memfun_deref, void (gui2::event::mouse_button<0ul>::*&)(gui2::event::ui_event, bool&, point const&), gui2::event::mouse_button<0ul>*&, gui2::event::ui_event&&, bool&, point const&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/invoke.h:74:14
    #27 0x55e22282957d in std::__invoke_result<void (gui2::event::mouse_button<0ul>::*&)(gui2::event::ui_event, bool&, point const&), gui2::event::mouse_button<0ul>*&, gui2::event::ui_event, bool&, point const&>::type std::__invoke<void (gui2::event::mouse_button<0ul>::*&)(gui2::event::ui_event, bool&, point const&), gui2::event::mouse_button<0ul>*&, gui2::event::ui_event, bool&, point const&>(void (gui2::event::mouse_button<0ul>::*&)(gui2::event::ui_event, bool&, point const&), gui2::event::mouse_button<0ul>*&, gui2::event::ui_event&&, bool&, point const&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/invoke.h:96:14
    #28 0x55e22282957d in void std::_Bind<void (gui2::event::mouse_button<0ul>::* (gui2::event::mouse_button<0ul>*, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<5>))(gui2::event::ui_event, bool&, point const&)>::__call<void, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, point const&, 0ul, 1ul, 2ul, 3ul>(std::tuple<gui2::widget&, gui2::event::ui_event&&, bool&, bool&, point const&>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/functional:506:11
    #29 0x55e222829270 in void std::_Bind<void (gui2::event::mouse_button<0ul>::* (gui2::event::mouse_button<0ul>*, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<5>))(gui2::event::ui_event, bool&, point const&)>::operator()<gui2::widget&, gui2::event::ui_event, bool&, bool&, point const&, void>(gui2::widget&, gui2::event::ui_event&&, bool&, bool&, point const&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/functional:591:17
    #30 0x55e222829270 in void std::__invoke_impl<void, std::_Bind<void (gui2::event::mouse_button<0ul>::* (gui2::event::mouse_button<0ul>*, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<5>))(gui2::event::ui_event, bool&, point const&)>&, gui2::widget&, gui2::event::ui_event, bool&, bool&, point const&>(std::__invoke_other, std::_Bind<void (gui2::event::mouse_button<0ul>::* (gui2::event::mouse_button<0ul>*, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<5>))(gui2::event::ui_event, bool&, point const&)>&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, point const&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/invoke.h:61:14
    #31 0x55e222829270 in std::enable_if<is_invocable_r_v<void, std::_Bind<void (gui2::event::mouse_button<0ul>::* (gui2::event::mouse_button<0ul>*, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<5>))(gui2::event::ui_event, bool&, point const&)>&, gui2::widget&, gui2::event::ui_event, bool&, bool&, point const&>, void>::type std::__invoke_r<void, std::_Bind<void (gui2::event::mouse_button<0ul>::* (gui2::event::mouse_button<0ul>*, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<5>))(gui2::event::ui_event, bool&, point const&)>&, gui2::widget&, gui2::event::ui_event, bool&, bool&, point const&>(std::_Bind<void (gui2::event::mouse_button<0ul>::* (gui2::event::mouse_button<0ul>*, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<5>))(gui2::event::ui_event, bool&, point const&)>&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, point const&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/invoke.h:111:2
    #32 0x55e222829270 in std::_Function_handler<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, point const&), std::_Bind<void (gui2::event::mouse_button<0ul>::* (gui2::event::mouse_button<0ul>*, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<5>))(gui2::event::ui_event, bool&, point const&)>>::_M_invoke(std::_Any_data const&, gui2::widget&, gui2::event::ui_event&&, bool&, bool&, point const&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/std_function.h:290:9
    #33 0x55e2227f5915 in std::function<void (gui2::widget&, gui2::event::ui_event, bool&, bool&, point const&)>::operator()(gui2::widget&, gui2::event::ui_event, bool&, bool&, point const&) const /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/std_function.h:591:9
    #34 0x55e2227f5915 in bool gui2::event::implementation::fire_event<(gui2::event::event_category)512, point const&>(gui2::event::ui_event, std::vector<std::pair<gui2::widget*, gui2::event::ui_event>, std::allocator<std::pair<gui2::widget*, gui2::event::ui_event>>> const&, gui2::widget*, gui2::widget*, point const&) /home/matthias/vcs/github/wesnoth/src/gui/core/event/dispatcher_private.hpp:262:4
    #35 0x55e2227e431f in bool gui2::event::fire_event<(gui2::event::event_category)512, point const&>(gui2::event::ui_event, gui2::event::dispatcher*, gui2::widget*, point const&) /home/matthias/vcs/github/wesnoth/src/gui/core/event/dispatcher_private.hpp:332:9
    #36 0x55e2227e0248 in gui2::event::dispatcher::fire(gui2::event::ui_event, gui2::widget&, point const&) /home/matthias/vcs/github/wesnoth/src/gui/core/event/dispatcher.cpp:100:9
    #37 0x55e222844760 in gui2::event::sdl_event_handler::mouse(gui2::event::ui_event, point const&) /home/matthias/vcs/github/wesnoth/src/gui/core/event/handler.cpp
    #38 0x55e2228451f3 in gui2::event::sdl_event_handler::mouse_button_up(point const&, unsigned char) /home/matthias/vcs/github/wesnoth/src/gui/core/event/handler.cpp
    #39 0x55e222843041 in gui2::event::sdl_event_handler::handle_event(SDL_Event const&) /home/matthias/vcs/github/wesnoth/src/gui/core/event/handler.cpp:400:5
    #40 0x55e223e01c5b in events::pump() /home/matthias/vcs/github/wesnoth/src/events.cpp:723:12
    #41 0x55e2219d64a5 in gui2::window::show(unsigned int) /home/matthias/vcs/github/wesnoth/src/gui/widgets/window.cpp:571:4
    #42 0x55e222a27818 in gui2::dialogs::modal_dialog::show(unsigned int) /home/matthias/vcs/github/wesnoth/src/gui/dialogs/modal_dialog.cpp:92:21
    #43 0x55e22134ccd6 in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&) /home/matthias/vcs/github/wesnoth/src/wesnoth.cpp:948:9
    #44 0x55e2213456ca in main /home/matthias/vcs/github/wesnoth/src/wesnoth.cpp:1175:19
    #45 0x7fd958827ccf  (/usr/lib/libc.so.6+0x27ccf) (BuildId: 316d0d3666387f0e8fb98773f51aa1801027c5ab)
    #46 0x7fd958827d89 in __libc_start_main (/usr/lib/libc.so.6+0x27d89) (BuildId: 316d0d3666387f0e8fb98773f51aa1801027c5ab)
    #47 0x55e221208fb4 in _start (/home/matthias/vcs/github/wesnoth/build/wesnoth+0x2c63fb4) (BuildId: 66de8149f937c5e6)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/matthias/vcs/github/wesnoth/src/gui/dialogs/achievements_dialog.cpp:165:3 in
```
