### ISSUE TITLE
segmentation fault on attack event (berserker)

### ISSUE THREAD

**Issue by andrzejskutela** [wesnoth/wesnoth#8115]
### Game and System Information

- **Version:** 1.16.10
- **Downloaded from:** github repo
- **Build info:** standard gentoo portage build
- **OS:** gentoo linux 6.4.3

### Description of the bug

```
[multiplayer]
    id="QQ_test"
    name="Crashing Wesnoth test"
    map_data="Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, 1 Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, 2 Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg"
    
    [side]
		side=1
		canrecruit=yes
		controller=human
		controller_lock=no
		team_name=a
		team_lock=true
		gold=75
		color=green
    [/side]
    [side]
		side=2
		canrecruit=yes
		controller=human
		controller_lock=no
		team_name=b
		team_lock=true
		gold=75
		color=red
    [/side]
    
    [event]
		name=start

		[unit]
			side=1
			type="Pikeman"
			x=3
			y=2
			id="pike"
		[/unit]
		
		[unit]
			side=1
			type="Dwarvish Berserker"
			x=2
			y=2
			id="serker"
		[/unit]

		[unit]
			side=2
			type="Jinn"
			x=4
			y=4
			id="jinn_champion"
		[/unit]

		[modify_unit]
			[filter]
				side=1
			[/filter]

			[object]
				silent=yes

				[effect]
					apply_to=attack
					increase_damage=-50%
					increase_accuracy=100
				[/effect]
			[/object]
		[/modify_unit]

		[modify_unit]
			[filter]
				id=jinn_champion
			[/filter]

			[object]
	 			silent=yes
	 			
	 			[effect]
				    apply_to=new_ability
				    [abilities]
						[dummy]
							id=qquws_medusa_spirit
							name="medusa gaze"
							description="When this unit defends, upon the first received hit it slows the opponent. When the opponent is already slowed and hits again, then it is turned into stone for two turns."
						[/dummy]
				    [/abilities]
				[/effect]
			[/object]
		[/modify_unit]
	[/event]

	[event]
		name=attacker hits
		first_time_only=no

		[filter_second]
			ability=qquws_medusa_spirit
		[/filter_second]
		[filter]
			[not]
				trait=immune_to_specials
			[/not]
		[/filter]
		[filter_condition]
			[variable]
				name=unit.hitpoints
				greater_than=0
			[/variable]
			[variable]
				name=second_unit.hitpoints
				greater_than=0
			[/variable]
		[/filter_condition]

		[if]
			[variable]
				name=unit.status.slowed
				boolean_equals=yes
			[/variable]
			[then]
				[if]
					[variable]
						name=unit.status.petrified
						boolean_equals=no
					[/variable]
					[then]
						[modify_unit]
							[filter]
								id=$unit.id
							[/filter]
							
							[status]
								petrified=yes
							[/status]
							
							[object]
								silent=yes
								duration=turn
								
								[effect]
								    apply_to=remove_attacks
								[/effect]
								[effect]
									apply_to=new_ability
									[abilities]
										[dummy]
											id=qquws_status_turned_to_stone
											name="<span color='#ab7b87'>turned to stone</span>"
											description="This unit gazed into the eyes of a medusa. The effect lasts for two turns."
										[/dummy]
									[/abilities]
								[/effect]
							[/object]
						[/modify_unit]
						
						[floating_text]
							x,y=$unit.x,$unit.y
							text="<span color='#ff0000'>petrified!</span>"
						[/floating_text]
					[/then]
				[/if]
			[/then]
			[else]
				[modify_unit]
					[filter]
						id=$unit.id
					[/filter]
					
					[status]
						slowed=yes
					[/status]
				[/modify_unit]
				
				[floating_text]
					x,y=$unit.x,$unit.y
					text="<span color='#ff0000'>slowed</span>"
				[/floating_text]
			[/else]
		[/if]
	[/event]
[/multiplayer]
```

### Steps to reproduce the behavior

1. copy the mock wml and start the game
2. on the first turn you get a pikeman and a serker to attack a jinn. Both your units have 100% chance to hit - irrelevant from the bug perspective, just make things easier to observe. Jinn as you will notice has "medusa gaze" ability.
3. when you attack the jinn with the pikeman, things work as expected
4. when you attack the jinn with the berserker, things just explode

### Expected behavior

attacking with the berserker ability should have the exact outcome as attacking without it

**Comment by andrzejskutela** [comment]
I just noticed there is qquws_lasting_effect_information variable used, I just copy pasted wml from the actual scenario and forgot to strip it down from everything unnecessary. I don't think wesnoth engine gets that far, and qquws_lasting_effect_information in this context is used only to un-petrify the unit after 2 turns.

**Comment by soliton-** [comment]
```
#0  0x0000555555b71460 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count(std::__weak_count<(__gnu_cxx::_Lock_policy)2> const&) [clone .lto_priv.0] ()
#1  0x0000555555cbbb4b in (anonymous namespace)::attack::perform_hit(bool, statistics_attack_context&) ()
#2  0x0000555555cbfd94 in attack_unit_and_advance(map_location const&, map_location const&, int, int, bool) ()
#3  0x0000555555bec4ff in synced_command_func_attack(config const&, bool, bool, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>) [clone .lto_priv.0] ()
#4  0x0000555555bf4bcf in synced_context::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, config const&, bool, bool, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>) ()
#5  0x0000555555bf4fdd in synced_context::run_and_store(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, config const&, bool, bool, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>) ()
#6  0x0000555555bf50f1 in synced_context::run_and_throw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, config const&, bool, bool, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>) ()
#7  0x0000555555e7a179 in events::mouse_handler::attack_enemy(map_location const&, map_location const&, int) ()
#8  0x0000555555e7ad90 in events::mouse_handler::move_action(bool) ()
#9  0x0000555555e6a765 in events::mouse_handler_base::clear_dragging(SDL_MouseButtonEvent const&, bool) ()
#10 0x0000555555e6e892 in events::mouse_handler_base::mouse_press(SDL_MouseButtonEvent const&, bool) ()
#11 0x0000555555d5c54d in controller_base::handle_event(SDL_Event const&) ()
#12 0x000055555601c2bf in events::pump() ()
#13 0x0000555555d60777 in controller_base::play_slice(bool) ()
#14 0x00005555560d4313 in play_controller::play_slice_catch() [clone .constprop.0] ()
#15 0x0000555555b58488 in playmp_controller::play_human_turn() ()
#16 0x0000555555b5a741 in playsingle_controller::play_side_impl() ()
#17 0x00005555559ce06e in campaign_controller::playmp_scenario(end_level_data&) ()
#18 0x00005555559d1640 in campaign_controller::play_game() ()
#19 0x00005555559c4f9c in mp::(anonymous namespace)::mp_manager::enter_create_mode() [clone .lto_priv.0] ()
#20 0x00005555559d7385 in game_launcher::play_multiplayer(game_launcher::mp_mode) ()
#21 0x000055555592e31b in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#22 0x000055555585cbd5 in main ()
```

**Comment by soliton-** [comment]
Still reproduces with
```
[multiplayer]
    id="QQ_test"
    name="Crashing Wesnoth test"
    map_data="Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, 1 Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, 2 Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg"
    
    [side]
                side=1
                canrecruit=yes
                controller=human
                controller_lock=no
                team_name=a
                team_lock=true
                gold=75
                color=green
    [/side]
    [side]
                side=2
                canrecruit=yes
                controller=human
                controller_lock=no
                team_name=b
                team_lock=true
                gold=75
                color=red
    [/side]
    
    [event]
                name=start

                [unit]
                        side=1
                        type="Dwarvish Berserker"
                        x=2
                        y=2
                        id="serker"
                [/unit]

                [unit]
                        side=2
                        type="Jinn"
                        x=4
                        y=4
                        id="jinn_champion"
                [/unit]

                [modify_unit]
                        [filter]
                                side=1
                        [/filter]

                        [object]
                                silent=yes

                                [effect]
                                        apply_to=attack
                                        increase_damage=-50%
                                        increase_accuracy=100
                                [/effect]
                        [/object]
                [/modify_unit]

                [modify_unit]
                        [filter]
                                id=jinn_champion
                        [/filter]

                        [object]
                                silent=yes
                                
                                [effect]
                                    apply_to=new_ability
                                    [abilities]
                                                [dummy]
                                                        id=qquws_medusa_spirit
                                                        name="medusa gaze"
                                                        description="When this unit defends, upon the first received hit it slows the opponent. When the opponent is already slowed and hits again, then it is turned into stone for two turns."
                                                [/dummy]
                                    [/abilities]
                                [/effect]
                        [/object]
                [/modify_unit]
        [/event]

        [event]
                name=attacker hits
                first_time_only=no

                [filter_second]
                        ability=qquws_medusa_spirit
                [/filter_second]
                [filter]
                        [not]
                                trait=immune_to_specials
                        [/not]
                [/filter]
                [modify_unit]
                        [filter]
                                id=$unit.id
                        [/filter]

                        [object]
                                silent=yes
                                duration=turn
                                
                                [effect]
                                    apply_to=remove_attacks
                                [/effect]
                        [/object]
                [/modify_unit]
        [/event]
[/multiplayer]
```

Presumably the issue is the attack removal mid battle.

**Comment by gfgtdf** [comment]
Probably https://github.com/wesnoth/wesnoth/commit/7f14cc57ee9d3aae474acb04a416bb519c28b1df is just missing in 1.16

**Comment by gfgtdf** [comment]
No wait, its there. hmm

**Comment by soliton-** [comment]
My backtrace is fom 1.17, btw. Segfaults there as well.
