### ISSUE TITLE
SIGFPE when the window size is smaller than the minimum size

### ISSUE THREAD

**Issue by guoshimin57** [wesnoth/wesnoth#8634]
### Game and System Information

- **Version: wesnoth-1.18.0**
- **OS: Fedora 39**
- I built (from sources) the game by myself with:

SDL2-2.28.5-1.fc39.x86_64
SDL2_image-2.8.1-1.fc39.x86_64
qemu-ui-sdl-8.1.3-1.fc39.x86_64
qemu-audio-sdl-8.1.3-1.fc39.x86_64
SDL2-devel-2.28.5-1.fc39.x86_64
SDL2_mixer-2.6.3-2.fc39.x86_64
SDL2_mixer-devel-2.6.3-2.fc39.x86_64
SDL2_image-devel-2.8.1-1.fc39.x86_64
SDL2_net-2.2.0-3.fc39.x86_64
SDL2-2.28.5-1.fc39.i686
gcc-13.2.1-6.fc39.x86_64
gcc-c++-13.2.1-6.fc39.x86_64

### Description of the bug

Wesnoth will crash when window size is smaller than 800*540. I use xprop command to get program specified minimum size. I use gdb to run wesnoth, and then set window to a small size (such as 500*1080), it will received signal SIGFPE, Arithmetic exception. bt command show:
Thread 1 "wesnoth" received signal SIGFPE, Arithmetic exception.
0x00005555562d9e1b in video::update_framebuffer() ()
#0  0x00005555562d9e1b in video::update_framebuffer() ()
#1  0x00005555562dd99c in video::update_buffers(bool) ()
#2  0x00005555561f1f7b in events::pump() ()
#3  0x0000555555c3b3e5 in gui2::window::show(unsigned int) ()
#4  0x0000555555d791a5 in gui2::dialogs::modal_dialog::show(unsigned int) ()
#5  0x0000555555a4aead in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#6  0x00005555559d6695 in main ()

### Steps to reproduce the behavior

1. run wesnoth
2. set wesnoth window size that smaller than 800*540 through the window manager.
(NOTE: Not all window managers can reproduce the behavior. Tiling window managers can force the window size to be smaller than a program-specified minimum size. I use gwm window manager : https://gsmwm.sf.net)
coredump detail Attach files.

### Expected behavior

SIGFPE when the window size is smaller than the minimum size

### Additional context

gsm@fc:~$ gdb wesnoth
GNU gdb (Fedora Linux) 14.1-1.fc39
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from wesnoth...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.fedoraproject.org/>
Enable debuginfod for this session? (y or [n]) 
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
(No debugging symbols found in wesnoth)
(gdb) r
Starting program: /usr/local/bin/wesnoth 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff32ed6c0 (LWP 53372)]
[New Thread 0x7fffee5666c0 (LWP 53373)]
[New Thread 0x7fffee5256c0 (LWP 53374)]
[New Thread 0x7fffed9576c0 (LWP 53394)]
[New Thread 0x7fffed0156c0 (LWP 53395)]
[New Thread 0x7fffec8146c0 (LWP 53396)]
[New Thread 0x7fffe19ff6c0 (LWP 53397)]
[New Thread 0x7fffe0dfe6c0 (LWP 53398)]
[New Thread 0x7fffc73ff6c0 (LWP 53399)]
[New Thread 0x7fffc6bfe6c0 (LWP 53400)]
[New Thread 0x7fffc63fd6c0 (LWP 53401)]
[New Thread 0x7fffc5bfc6c0 (LWP 53402)]
[Thread 0x7fffc5bfc6c0 (LWP 53402) exited]
[Thread 0x7fffc63fd6c0 (LWP 53401) exited]
[Thread 0x7fffc6bfe6c0 (LWP 53400) exited]
[New Thread 0x7fffc6bfe6c0 (LWP 53403)]
[New Thread 0x7fffc63fd6c0 (LWP 53404)]
[New Thread 0x7fffc5bfc6c0 (LWP 53405)]
[New Thread 0x7fffc4ffb6c0 (LWP 53421)]
[Thread 0x7fffc4ffb6c0 (LWP 53421) exited]
[New Thread 0x7fffc4ffb6c0 (LWP 53422)]
[New Thread 0x7fff9ffff6c0 (LWP 53423)]
[Thread 0x7fffc4ffb6c0 (LWP 53422) exited]
[Thread 0x7fff9ffff6c0 (LWP 53423) exited]
[New Thread 0x7fff9ffff6c0 (LWP 53424)]
[New Thread 0x7fffc4ffb6c0 (LWP 53425)]
[Thread 0x7fff9ffff6c0 (LWP 53424) exited]
[New Thread 0x7fff9ffff6c0 (LWP 53426)]
[New Thread 0x7fff9f1ff6c0 (LWP 53427)]
[Thread 0x7fff9ffff6c0 (LWP 53426) exited]
[Thread 0x7fffc4ffb6c0 (LWP 53425) exited]
[New Thread 0x7fffc4ffb6c0 (LWP 53428)]
[New Thread 0x7fff9ffff6c0 (LWP 53429)]
[Thread 0x7fff9f1ff6c0 (LWP 53427) exited]
[Thread 0x7fffc4ffb6c0 (LWP 53428) exited]
[New Thread 0x7fffc4ffb6c0 (LWP 53430)]
[New Thread 0x7fff9f1ff6c0 (LWP 53431)]
[Thread 0x7fffc4ffb6c0 (LWP 53430) exited]
[Thread 0x7fff9ffff6c0 (LWP 53429) exited]
[Thread 0x7fff9f1ff6c0 (LWP 53431) exited]
[New Thread 0x7fff9f1ff6c0 (LWP 53432)]
[New Thread 0x7fff9ffff6c0 (LWP 53433)]
[Thread 0x7fff9f1ff6c0 (LWP 53432) exited]
[New Thread 0x7fff9f1ff6c0 (LWP 53434)]
[New Thread 0x7fffc4ffb6c0 (LWP 53435)]
[Thread 0x7fff9ffff6c0 (LWP 53433) exited]
[Thread 0x7fff9f1ff6c0 (LWP 53434) exited]
[Thread 0x7fffc4ffb6c0 (LWP 53435) exited]
[New Thread 0x7fffc4ffb6c0 (LWP 53436)]
[New Thread 0x7fff9f1ff6c0 (LWP 53437)]
[Thread 0x7fffc4ffb6c0 (LWP 53436) exited]
[Thread 0x7fff9f1ff6c0 (LWP 53437) exited]
[New Thread 0x7fff9f1ff6c0 (LWP 53438)]
[New Thread 0x7fffc4ffb6c0 (LWP 53439)]
[Thread 0x7fff9f1ff6c0 (LWP 53438) exited]
[New Thread 0x7fff9f1ff6c0 (LWP 53440)]
[New Thread 0x7fff9ffff6c0 (LWP 53441)]
[Thread 0x7fffc4ffb6c0 (LWP 53439) exited]
[Thread 0x7fff9f1ff6c0 (LWP 53440) exited]
[New Thread 0x7fff9f1ff6c0 (LWP 53442)]
[New Thread 0x7fffc4ffb6c0 (LWP 53443)]
[Thread 0x7fff9ffff6c0 (LWP 53441) exited]
[Thread 0x7fff9f1ff6c0 (LWP 53442) exited]
[Thread 0x7fffc4ffb6c0 (LWP 53443) exited]
[New Thread 0x7fffc4ffb6c0 (LWP 53444)]
[New Thread 0x7fff9f1ff6c0 (LWP 53445)]
[Thread 0x7fffc4ffb6c0 (LWP 53444) exited]
[New Thread 0x7fffc4ffb6c0 (LWP 53446)]
[Thread 0x7fff9f1ff6c0 (LWP 53445) exited]
[New Thread 0x7fff9f1ff6c0 (LWP 53447)]
[Thread 0x7fffc4ffb6c0 (LWP 53446) exited]
[Thread 0x7fff9f1ff6c0 (LWP 53447) exited]
[New Thread 0x7fff9f1ff6c0 (LWP 53448)]
[New Thread 0x7fffc4ffb6c0 (LWP 53449)]
[Thread 0x7fff9f1ff6c0 (LWP 53448) exited]
[Thread 0x7fffc4ffb6c0 (LWP 53449) exited]
[New Thread 0x7fffc4ffb6c0 (LWP 53450)]
[New Thread 0x7fff9f1ff6c0 (LWP 53451)]
[Thread 0x7fffc4ffb6c0 (LWP 53450) exited]
[Thread 0x7fff9f1ff6c0 (LWP 53451) exited]
[New Thread 0x7fff9f1ff6c0 (LWP 53452)]
[New Thread 0x7fffc4ffb6c0 (LWP 53453)]
[Thread 0x7fff9f1ff6c0 (LWP 53452) exited]
[New Thread 0x7fff9f1ff6c0 (LWP 53454)]
[New Thread 0x7fff9ffff6c0 (LWP 53455)]
[Thread 0x7fffc4ffb6c0 (LWP 53453) exited]
[Thread 0x7fff9f1ff6c0 (LWP 53454) exited]
[New Thread 0x7fff9f1ff6c0 (LWP 53456)]
[New Thread 0x7fffc4ffb6c0 (LWP 53457)]
[Thread 0x7fff9ffff6c0 (LWP 53455) exited]
[Thread 0x7fff9f1ff6c0 (LWP 53456) exited]
[Thread 0x7fffc4ffb6c0 (LWP 53457) exited]
[New Thread 0x7fffc4ffb6c0 (LWP 53458)]
[New Thread 0x7fff9f1ff6c0 (LWP 53459)]
[Thread 0x7fffc4ffb6c0 (LWP 53458) exited]
[New Thread 0x7fffc4ffb6c0 (LWP 53460)]
[New Thread 0x7fff9ffff6c0 (LWP 53461)]
[Thread 0x7fffc4ffb6c0 (LWP 53460) exited]
[Thread 0x7fff9f1ff6c0 (LWP 53459) exited]
[Thread 0x7fff9ffff6c0 (LWP 53461) exited]
[New Thread 0x7fff9ffff6c0 (LWP 53462)]
[New Thread 0x7fff9f1ff6c0 (LWP 53463)]
[Thread 0x7fff9ffff6c0 (LWP 53462) exited]
[Thread 0x7fff9f1ff6c0 (LWP 53463) exited]
[New Thread 0x7fff9f1ff6c0 (LWP 53464)]
[New Thread 0x7fff9ffff6c0 (LWP 53465)]
[Thread 0x7fff9f1ff6c0 (LWP 53464) exited]
[New Thread 0x7fff9f1ff6c0 (LWP 53466)]
[New Thread 0x7fffc4ffb6c0 (LWP 53467)]
[Thread 0x7fff9ffff6c0 (LWP 53465) exited]
[Thread 0x7fff9f1ff6c0 (LWP 53466) exited]
[Thread 0x7fffc4ffb6c0 (LWP 53467) exited]
[New Thread 0x7fffc4ffb6c0 (LWP 53468)]
[New Thread 0x7fff9f1ff6c0 (LWP 53469)]
[Thread 0x7fffc4ffb6c0 (LWP 53468) exited]
[Thread 0x7fff9f1ff6c0 (LWP 53469) exited]

Thread 1 "wesnoth" received signal SIGFPE, Arithmetic exception.
0x00005555562d9e1b in video::update_framebuffer() ()
Missing separate debuginfos, use: dnf debuginfo-install SDL2-2.28.5-1.fc39.x86_64 SDL2_image-2.8.1-1.fc39.x86_64 SDL2_mixer-2.6.3-2.fc39.x86_64 boost-atomic-1.81.0-8.fc39.x86_64 boost-chrono-1.81.0-8.fc39.x86_64 boost-context-1.81.0-8.fc39.x86_64 boost-coroutine-1.81.0-8.fc39.x86_64 boost-filesystem-1.81.0-8.fc39.x86_64 boost-iostreams-1.81.0-8.fc39.x86_64 boost-locale-1.81.0-8.fc39.x86_64 boost-program-options-1.81.0-8.fc39.x86_64 boost-random-1.81.0-8.fc39.x86_64 boost-regex-1.81.0-8.fc39.x86_64 boost-system-1.81.0-8.fc39.x86_64 boost-thread-1.81.0-8.fc39.x86_64 bzip2-libs-1.0.8-16.fc39.x86_64 cairo-1.18.0-1.fc39.x86_64 dbus-libs-1.14.10-1.fc39.x86_64 expat-2.5.0-3.fc39.x86_64 flac-libs-1.4.3-2.fc39.x86_64 fontconfig-2.14.2-5.fc39.x86_64 freetype-2.13.1-2.fc39.x86_64 fribidi-1.0.13-2.fc39.x86_64 glib2-2.78.3-1.fc39.x86_64 glibc-2.38-14.fc39.x86_64 graphite2-1.3.14-12.fc39.x86_64 gsm-1.0.22-3.fc39.x86_64 harfbuzz-8.2.1-2.fc39.x86_64 jbigkit-libs-2.1-26.fc39.x86_64 keyutils-libs-1.6.1-7.fc39.x86_64 krb5-libs-1.21.2-2.fc39.x86_64 lame-libs-3.100-15.fc39.x86_64 libX11-1.8.7-1.fc39.x86_64 libX11-xcb-1.8.7-1.fc39.x86_64 libXau-1.0.11-3.fc39.x86_64 libXext-1.3.5-3.fc39.x86_64 libXfixes-6.0.0-6.fc39.x86_64 libXrender-0.9.11-3.fc39.x86_64 libblkid-2.39.3-1.fc39.x86_64 libbrotli-1.1.0-1.fc39.x86_64 libcom_err-1.47.0-2.fc39.x86_64 libcurl-minimal-8.2.1-4.fc39.x86_64 libdecor-0.2.1-2.fc39.x86_64 libdrm-2.4.117-1.fc39.x86_64 libedit-3.1-48.20230828cvs.fc39.x86_64 libffi-3.4.4-4.fc39.x86_64 libgcc-13.2.1-6.fc39.x86_64 libglvnd-1.7.0-1.fc39.x86_64 libglvnd-glx-1.7.0-1.fc39.x86_64 libicu-73.2-2.fc39.x86_64 libjpeg-turbo-2.1.4-3.fc39.x86_64 liblerc-4.0.0-4.fc39.x86_64 libmount-2.39.3-1.fc39.x86_64 libpciaccess-0.16-9.fc39.x86_64 libpng-1.6.37-15.fc39.x86_64 libselinux-3.5-5.fc39.x86_64 libstdc++-13.2.1-6.fc39.x86_64 libthai-0.1.29-6.fc39.x86_64 libtiff-4.4.0-8.fc39.x86_64 libunistring-1.1-5.fc39.x86_64 libvorbis-1.3.7-8.fc39.x86_64 libwayland-client-1.22.0-2.fc39.x86_64 libwayland-egl-1.22.0-2.fc39.x86_64 libwebp-1.3.2-2.fc39.x86_64 libxcb-1.13.1-12.fc39.x86_64 libxshmfence-1.3-13.fc39.x86_64 llvm-libs-17.0.6-1.fc39.x86_64 lz4-libs-1.9.4-4.fc39.x86_64 openssl1.1-1.1.1q-5.fc39.x86_64 opus-1.3.1-13.fc39.x86_64 pango-1.51.0-1.fc39.x86_64 pcre2-10.42-1.fc39.2.x86_64 pixman-0.42.2-2.fc39.x86_64 pulseaudio-libs-16.1-5.fc39.x86_64 readline-8.2-4.fc39.x86_64 xz-libs-5.4.4-1.fc39.x86_64 zlib-1.2.13-4.fc39.x86_64
(gdb) bt
#0  0x00005555562d9e1b in video::update_framebuffer() ()
#1  0x00005555562dd99c in video::update_buffers(bool) ()
#2  0x00005555561f1f7b in events::pump() ()
#3  0x0000555555c3b3e5 in gui2::window::show(unsigned int) ()
#4  0x0000555555d791a5 in gui2::dialogs::modal_dialog::show(unsigned int) ()
#5  0x0000555555a4aead in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#6  0x00005555559d6695 in main ()
(gdb) q
A debugging session is active.

	Inferior 1 [process 53369] will be killed.

Quit anyway? (y or n) 
Please answer y or n.
A debugging session is active.

	Inferior 1 [process 53369] will be killed.

Quit anyway? (y or n) y

**Comment by Pentarctagon** [comment]
Is this using Wayland?

**Comment by guoshimin57** [comment]
No. I using X11.

**Comment by guoshimin57** [comment]
coredump file seems too larg (340MB). I can not upload.

**Comment by guoshimin57** [comment]
[coredump.tar.gz](https://github.com/wesnoth/wesnoth/files/14761001/coredump.tar.gz)

**Comment by Pentarctagon** [comment]
@loonycyborg not sure if it's at all related to what you're seeing on Wayland+Flatpak, but it's another SIGFPE.

**Comment by loonycyborg** [comment]
Yes probably issue #8605 has the same mechanism.

**Comment by guoshimin57** [comment]
It's native built with cmake, and run on X11. wesnoth-1.16.6 to wesnoth-1.16.9 have similar bug, but only triggered on homepage.

**Comment by Wedge009** [comment]
If only because this is specific to window sizes smaller than the minimum, I thought of #2990 as that one also appears to be specific to less-common window managers.

**Comment by guoshimin57** [comment]
I think it is a design flaw to force quit when the window size is smaller than the minimum specified by the program. At least it should pop up a warning window after resizing to the size specified by the window manager. If the user does not listen to the warning, it is not too late to force quit. A more portable approach is to set the appropriate window properties, such as _NET_WM_STATE_ABOVE or _NET_WM_STATE_MODAL, when wesnoth know the window is set to a small size, then request to normal size. In this case, most window managers (all window managers that comply with the EWMH specification) will respect the program-specified minimum limit.

**Comment by Wedge009** [comment]
A graceful failure would be preferable, of course, but the minimum specifications are there for a reason - support shouldn't be expected for resources below those specs.
